import "./review.css";
import { zipSync } from "fflate";
import { DEFAULT_PALETTE_LAYOUT, MAP_ASSET_CATALOG } from "../game/mapAssetCatalog.generated";
import { addMarker, cloneMap, createManualMap, MapRepository, normalizeMap, storeTrialMapPack, validateMap, validateTrialMapPack, type ManualLayer, type MapDocument, type MapMarker, type MapMarkerKind } from "../game/mapDocument";
import { MAX_PALETTE_DIMENSION, PaletteHistory, paletteTagSummary, tagPaletteRegion, addPalettePage, clonePaletteLayout, createPalettePage, deletePalettePage, fillPaletteStamp, paintPaletteStamp, paletteRectFromPoints, paletteStamp, placeSourceFrames, rectanglePaletteStamp, renamePalettePage, resizePalettePage, selectCompatiblePalettePageId, transferPaletteRegion, validatePaletteLayout, type CellPoint, type CellRect, type PaletteAsset, type PaletteCellRole, type PaletteCellStatus, type PaletteLayout, type PalettePage } from "./paletteModel";
import { fitEditorCanvas, sparseGridExtent } from "./canvasSizing";
import { applyMapSettingsAtomically } from "./mapSettings";
import { applyDungeonFloorUpdates, planDungeonFloorCompaction, planDungeonFloorMove, smallestMissingDungeonFloor } from "./floorSequence";
import { ACTOR_CATALOG, actorEnemyStatsAt, actorHasEnemyStats, actorSupportsDirectionalMovement, applyActorSettings, currentActorSettings } from "../game/actorCatalog";
import { ACTOR_ARCHETYPES, ACTOR_TIERS, enemyStatsAt, type ActorArchetype, type ActorTier } from "../game/dungeonDifficulty";
import type { ActorSettingsCatalog } from "../game/actorSettings";
import type { CraftpixActorClip, CraftpixActorDefinition } from "../game/craftpixActors";
import { advanceActorPreview, actorPreviewActions, actorPreviewDirections, actorPreviewFrameRect, actorPreviewPath, type ActorPreviewState } from "./actorPreview";
import { createDefaultMapPack } from "../game/defaultMapPack";
import { DungeonThemeEditor } from "./dungeonThemeEditor";
import { SpawnTableEditor } from "./spawnEditor";

const root = document.querySelector<HTMLElement>("#review-app");
if (!root) throw new Error("review app root not found");
const editorRoot = root;

let assets: PaletteAsset[] = MAP_ASSET_CATALOG.map((asset) => ({ ...asset, mapKinds: [...asset.mapKinds] }));
let assetById = new Map(assets.map((asset) => [asset.id, asset]));
const selectedAssetStorageKey = "map-editor:selected-asset";
const repository = new MapRepository();
const layers: ManualLayer[] = ["ground", "structure", "decoration"];
const homeMarkers: MapMarkerKind[] = ["homeSpawn", "dungeonEntrance", "homePreparation", "homeVisitors", "shopkeeperCounter", "customerCounter"];
const dungeonMarkers: MapMarkerKind[] = ["stairsUp", "stairsDown"];
const sourceScale = 2;
const ARCHETYPE_LABELS: Record<ActorArchetype, string> = { brute: "重", swarm: "群", caster: "術", lurker: "伏" };
const TAG_ROLE_LABELS: Record<PaletteCellRole, string> = { floor: "床", wall: "壁", prop: "小物", stairs: "階段", liquid: "水・溶岩" };

root.innerHTML = `
  <div class="map-editor-shell">
    <header class="map-editor-header"><div><p class="map-editor-eyebrow">AUTOGENERATED DUNGEON CONTENT</p><h1>自動生成アセット・マップエディター</h1><p>素材とパレット、ダンジョンテーマを整備し、ローグライクの自動生成へ反映します。</p></div>
      <div class="map-editor-header-actions" data-manual-map-actions hidden><button data-action="new">新規マップ</button><button data-action="rename">名前変更</button><button data-action="duplicate">複製</button><button data-action="delete">削除</button><button data-action="undo">元に戻す</button><button data-action="redo">やり直す</button><button class="primary" data-action="try">編集マップでゲーム開始</button><span class="game-start-status" data-game-start-status></span></div></header>
    <nav class="editor-mode-tabs" aria-label="エディターモード"><button class="active" data-editor-mode="palette">素材パレット編集</button><button data-editor-mode="themes">ダンジョンテーマ</button><button data-editor-mode="actors">キャラクター</button><button data-editor-mode="spawns">出現表</button><button data-editor-mode="map">手動マップ（任意）</button></nav>
    <p class="editor-global-status save-status" data-status>素材とパレットを読み込み中…</p>
    <section data-editor-view="map" hidden>
      <section class="map-editor-toolbar">
        <label>一覧表示 <select data-kind><option value="home">家</option><option value="dungeon">ダンジョン</option></select></label>
        <label>マップ種類 <select data-map-kind><option value="home">家</option><option value="dungeon">ダンジョン</option></select></label><label data-floor-field>地下階 <input data-map-floor type="number" min="1" step="1"></label><button data-action="apply-floor" type="button">階層を変更</button><label>幅 <input data-map-width type="number" min="4" max="256"></label><label>高さ <input data-map-height type="number" min="4" max="256"></label>
        <label>セル <select data-tile-size><option value="16">16px</option><option value="32">32px</option></select></label><button data-action="apply-map-settings">サイズを適用</button>
        <label>道具 <select data-tool><option value="paint">鉛筆（スタンプ）</option><option value="rectangle">矩形（繰り返し）</option><option value="fill">塗りつぶし（単体のみ）</option><option value="erase">消去</option><option value="eyedropper">スポイト</option><option value="marker">マーカー</option><option value="collision-walkable">通行可</option><option value="collision-blocked">通行不可</option></select></label>
        <label class="check"><input type="checkbox" data-grid checked>グリッド</label><label class="check"><input type="checkbox" data-pass checked>通行表示</label><span class="collision-legend" aria-label="通行表示の凡例"><span class="walkable"></span>通行可 <span class="blocked"></span>通行不可</span><label>ズーム <select data-zoom><option value="1">100%</option><option value="1.5">150%</option><option value="2">200%</option></select></label>
      </section>
      <main class="map-editor-layout">
        <aside class="map-editor-side"><div class="panel-heading"><h2>マップ</h2><span data-map-count></span></div><div class="map-list" data-map-list></div><div class="map-actions"><button data-action="export-map">現在JSON</button><button data-action="export-pack">試遊パックJSON</button><label class="file-button">JSON読込<input type="file" accept="application/json" data-import></label></div><hr>
          <h2>レイヤー</h2><label>作業対象 <select data-layer><option value="ground">ground（床）</option><option value="structure">structure（壁・構造物）</option><option value="decoration">decoration（装飾）</option></select></label><div class="layer-visibility" aria-label="レイヤーの可視設定"><label><input type="checkbox" data-layer-visible="ground" checked>groundを表示</label><label><input type="checkbox" data-layer-visible="structure" checked>structureを表示</label><label><input type="checkbox" data-layer-visible="decoration" checked>decorationを表示</label></div><p class="small">配置・消去・スポイトは作業対象レイヤーだけに作用します。表示チェックは編集データを消さず、キャンバス上の表示だけを切り替えます。</p><hr>
          <h2>マーカー</h2><label>種類 <select data-marker></select></label><p class="small">マーカー道具でセルをクリックします。店主の開店位置は「店主カウンター」、客の接客位置は「客カウンター」で指定します。stairsUp / stairsDownには、パレットの単一セルを見た目として設定します。</p><div hidden data-enemy-roster></div><p hidden data-enemy-roster-status></p></aside>
        <section class="map-canvas-panel"><div class="panel-heading"><h2 data-map-title>マップ</h2><span data-stamp-info>スタンプ未選択</span></div><p class="canvas-fit-warning" data-canvas-fit hidden></p><div class="map-canvas-wrap"><canvas data-map-canvas></canvas></div><div class="map-canvas-help">パレットの画像セルをクリックして選び、マップへ配置します。鉛筆は選択矩形の左上を配置、矩形は選択パターンを繰り返します。素材がマップ外へ出る操作は全体を拒否します。</div><div class="map-validation" data-validation></div></section>
        <div class="palette-host" data-palette-host="map"><aside class="map-editor-side palette-panel"><div class="panel-heading"><h2>自由配置パレット</h2><div class="palette-heading-actions"><span data-palette-dirty></span><button class="palette-add-current" data-action="palette-add-current" type="button">新規パレット</button><button class="palette-save-current primary" data-action="palette-save" type="button">変更を保存</button><button class="palette-delete-current" data-action="palette-delete" type="button">このパレットを削除</button></div></div><div class="palette-tabs" data-palette-tabs role="listbox" aria-label="パレット"></div><details class="palette-menu"><summary>パレットの管理</summary><div class="palette-actions"><button data-action="palette-add">ページ追加</button><button data-action="palette-rename">改名</button><button data-action="palette-resize">拡縮</button><button data-action="palette-undo">戻す</button><button data-action="palette-redo">やり直し</button><button data-action="palette-reload">再読込</button><button data-action="palette-export">JSON書出し</button></div></details><div class="palette-wrap"><canvas data-palette-canvas></canvas></div>
          <p class="small">パレットの画像セルをクリックして選び、マップへ配置します。選択範囲をドラッグすると移動、Shift+ドラッグで複製、Deleteで削除できます。</p></aside></div>
      </main>
      <section class="actor-roster-strip" data-map-actor-strip><div class="panel-heading"><div><h2>このダンジョンに出現する敵</h2><p class="small">画像カードで出現候補を切り替えます。主人公は常に登場するため、この一覧には含みません。</p></div><span data-map-actor-strip-status></span></div><div class="actor-roster-strip-list" data-map-actor-strip-list></div></section>
    </section>
    <section class="palette-editor-view" data-editor-view="palette"><div class="palette-editor-toolbar"><span>素材取込からパレット作成・保存までをここで行います。保存したパレットはダンジョンテーマと自動生成設定から参照できます。</span></div><div class="palette-tag-toolbar"><span class="palette-tag-label">選択範囲の仕分け</span><label>用途 <select data-tag-role><option value="">変更しない</option><option value="floor">床</option><option value="wall">壁</option><option value="prop">小物</option><option value="stairs">階段</option><option value="liquid">水・溶岩</option><option value="-">未設定に戻す</option></select></label><label>状態 <select data-tag-status><option value="">変更しない</option><option value="ready">使える</option><option value="unsorted">未整理</option><option value="rejected">不採用</option></select></label><input data-tag-note placeholder="不採用の理由（任意）" aria-label="不採用の理由"><button type="button" data-action="palette-tag">選択範囲へ適用</button><span class="palette-tag-summary" data-tag-summary></span></div><div class="palette-workspace"><section class="asset-folder-panel" data-asset-folder><div class="panel-heading"><div><h2>素材フォルダ（Project）</h2><p class="small">ZIP／TMX／PNGを登録し、タイルをパレットへドラッグします。</p></div><span data-asset-folder-status></span></div><div class="asset-import-toolbar"><label class="file-button">素材を取り込む<input type="file" accept=".zip,.tmx,.tsx,.png" multiple data-asset-import></label><span>登録時に素材別パレットを自動作成します。</span></div><div data-import-report></div><div class="asset-filter-toolbar"><div class="asset-size-filters" role="group" aria-label="素材のセルサイズ"><button type="button" class="active" data-asset-size-filter="all">すべて</button><button type="button" data-asset-size-filter="16">16px</button><button type="button" data-asset-size-filter="32">32px</button></div><input type="search" data-asset-search placeholder="素材名を検索" aria-label="素材名を検索"><button type="button" data-action="asset-refresh">一覧更新</button></div><select class="visually-hidden" data-asset aria-label="素材シート"></select><div class="asset-browser"><nav class="asset-image-picker" data-asset-picker aria-label="素材フォルダ"></nav><div class="asset-content"><div class="source-wrap asset-source-wrap"><canvas data-source-canvas></canvas></div><p class="small">左の画像を選択し、方眼で単体または矩形を選んで右の同じセルサイズのパレットへドラッグします。</p></div></div></section><div class="palette-host" data-palette-host="palette"></div></div></section>
    <section class="actor-editor-view" data-editor-view="actors" hidden>
      <div class="actor-editor-grid"><aside class="map-editor-side actor-library-panel"><div class="panel-heading"><div><h2>キャラクター素材</h2><p class="small">画像を選ぶと右側でアニメーションと能力値を確認できます。素材の追加は素材パレット編集タブから行います。</p></div><span data-actor-library-count></span></div><div class="actor-preview-list" data-actor-preview-list></div></aside><section class="map-editor-side actor-detail-panel"><div class="panel-heading"><h2>キャラクター確認・設定</h2><span data-actor-preview-status></span></div><div class="actor-preview-controls"><select class="visually-hidden" data-actor-preview-id aria-label="キャラクター"></select><label>動作 <select data-actor-preview-action></select></label><label>方向 <select data-actor-preview-direction></select></label></div><canvas class="actor-preview-canvas" data-actor-preview-canvas width="320" height="320"></canvas><div data-actor-settings></div><button data-action="actor-settings-save">能力値・役割を保存</button><p class="small" data-actor-settings-status></p></section></div>
    </section>
    <section class="theme-editor-view" data-editor-view="themes" hidden data-theme-editor></section>
    <section class="spawn-editor-view" data-editor-view="spawns" hidden data-spawn-editor></section>
  </div>`;

const themeEditorHost = root.querySelector<HTMLElement>("[data-theme-editor]");
if (!themeEditorHost) throw new Error("theme editor root not found");
new DungeonThemeEditor(themeEditorHost, assets);
const spawnEditorHost = root.querySelector<HTMLElement>("[data-spawn-editor]");
if (!spawnEditorHost) throw new Error("spawn editor root not found");
const spawnEditor = new SpawnTableEditor(spawnEditorHost);

const q = <T extends Element>(selector: string): T => { const result = root.querySelector<T>(selector); if (!result) throw new Error(`missing editor element: ${selector}`); return result; };
const mapCanvas = q<HTMLCanvasElement>("[data-map-canvas]"), mapContext = mapCanvas.getContext("2d")!;
const paletteCanvas = q<HTMLCanvasElement>("[data-palette-canvas]"), paletteContext = paletteCanvas.getContext("2d")!;
const sourceCanvas = q<HTMLCanvasElement>("[data-source-canvas]"), sourceContext = sourceCanvas.getContext("2d")!;
const mapList = q<HTMLElement>("[data-map-list]"), paletteTabs = q<HTMLElement>("[data-palette-tabs]"), validation = q<HTMLElement>("[data-validation]"), status = q<HTMLElement>("[data-status]");
const mapCount = q<HTMLElement>("[data-map-count]"), mapTitle = q<HTMLElement>("[data-map-title]"), stampInfo = q<HTMLElement>("[data-stamp-info]"), paletteDirty = q<HTMLElement>("[data-palette-dirty]"), canvasFitWarning = q<HTMLElement>("[data-canvas-fit]"), gameStartStatus = q<HTMLElement>("[data-game-start-status]"), enemyRoster = q<HTMLElement>("[data-enemy-roster]"), enemyRosterStatus = q<HTMLElement>("[data-enemy-roster-status]"), importReport = q<HTMLElement>("[data-import-report]"), actorPreviewStatus = q<HTMLElement>("[data-actor-preview-status]"), actorSettings = q<HTMLElement>("[data-actor-settings]"), actorSettingsStatus = q<HTMLElement>("[data-actor-settings-status]"), assetPicker = q<HTMLElement>("[data-asset-picker]"), assetFolderStatus = q<HTMLElement>("[data-asset-folder-status]"), paletteActorStrip = q<HTMLElement>("[data-map-actor-strip]"), paletteActorStripList = q<HTMLElement>("[data-map-actor-strip-list]"), paletteActorStripStatus = q<HTMLElement>("[data-map-actor-strip-status]"), actorPreviewList = q<HTMLElement>("[data-actor-preview-list]"), actorLibraryCount = q<HTMLElement>("[data-actor-library-count]");
const kind = q<HTMLSelectElement>("[data-kind]"), mapKind = q<HTMLSelectElement>("[data-map-kind]"), mapFloor = q<HTMLInputElement>("[data-map-floor]"), mapWidth = q<HTMLInputElement>("[data-map-width]"), mapHeight = q<HTMLInputElement>("[data-map-height]"), tileSize = q<HTMLSelectElement>("[data-tile-size]"), layer = q<HTMLSelectElement>("[data-layer]"), tool = q<HTMLSelectElement>("[data-tool]"), marker = q<HTMLSelectElement>("[data-marker]"), zoom = q<HTMLSelectElement>("[data-zoom]"), assetSelect = q<HTMLSelectElement>("[data-asset]"), importInput = q<HTMLInputElement>("[data-import]");
const floorField = q<HTMLElement>("[data-floor-field]"), applyFloorButton = q<HTMLButtonElement>("[data-action=apply-floor]");
const grid = q<HTMLInputElement>("[data-grid]"), pass = q<HTMLInputElement>("[data-pass]"), assetImportInput = q<HTMLInputElement>("[data-asset-import]"), assetSearch = q<HTMLInputElement>("[data-asset-search]"), actorPreviewId = q<HTMLSelectElement>("[data-actor-preview-id]"), actorPreviewAction = q<HTMLSelectElement>("[data-actor-preview-action]"), actorPreviewDirection = q<HTMLSelectElement>("[data-actor-preview-direction]"), actorPreviewCanvas = q<HTMLCanvasElement>("[data-actor-preview-canvas]"), actorPreviewContext = actorPreviewCanvas.getContext("2d")!;
const layerVisibility = new Map([...root.querySelectorAll<HTMLInputElement>("[data-layer-visible]")].map((input) => [input.dataset.layerVisible as ManualLayer, input]));
const tagRole = q<HTMLSelectElement>("[data-tag-role]"), tagStatus = q<HTMLSelectElement>("[data-tag-status]"), tagNote = q<HTMLInputElement>("[data-tag-note]"), tagSummary = q<HTMLElement>("[data-tag-summary]");
const palettePanel = q<HTMLElement>(".palette-panel"), paletteSaveButton = q<HTMLButtonElement>("[data-action=palette-save]"), manualMapActions = q<HTMLElement>("[data-manual-map-actions]");

let maps: MapDocument[] = [], active: MapDocument | undefined;
let palettes = new PaletteHistory(clonePaletteLayout(DEFAULT_PALETTE_LAYOUT as unknown as PaletteLayout));
let activePageId = "", selectedAssetId = sessionStorage.getItem(selectedAssetStorageKey) ?? "";
let revealSelectedAsset = selectedAssetId.length > 0;
let sourceRect: CellRect | undefined, paletteRect: CellRect | undefined, mapStart: CellPoint | undefined;
let mapDragging = false, mapLastApplied: CellPoint | undefined;
let sourceDrag: { start: CellPoint; moved: boolean; existing: boolean } | undefined;
let paletteDrag: { start: CellPoint; moved: boolean; original?: CellRect } | undefined;
let mapCellPixels = 16, paletteCellPixels = 16, sourceCellPixels = 16, paletteRenderedColumns = 1, paletteRenderedRows = 1;
let pendingImport: { id: string; analysis: any } | undefined;
let loadedActorSettings: ActorSettingsCatalog = currentActorSettings();
let actorPreviewState: ActorPreviewState = { action: "idle", direction: "down", frame: 0, elapsedMs: 0 };
let actorPreviewLastTime = 0;
type EditorMode = "map" | "palette" | "themes" | "actors" | "spawns";
type AssetSizeFilter = "all" | "16" | "32";
let editorMode: EditorMode = "palette";
let assetSizeFilter: AssetSizeFilter = "all", assetSearchQuery = "";
const actorPreviewImages = new Map<string, HTMLImageElement>();
const mapHistory = new Map<string, { undo: MapDocument[]; redo: MapDocument[] }>(), images = new Map<string, HTMLImageElement>();
for (const asset of assets) { const image = new Image(); image.onload = () => render(); image.src = asset.path; images.set(asset.id, image); }

const uniqueId = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
const activePage = (): PalettePage | undefined => palettes.layout.pages.find((page) => page.id === activePageId);
const catalogAsset = (id: string) => assetById.get(id);
const pageForActiveMap = (): PalettePage | undefined => { const current = active; return current ? palettes.layout.pages.find((page) => page.id === activePageId && page.tileSize === current.tileSize) : undefined; };
const pageForEditor = (): PalettePage | undefined => editorMode === "palette" ? activePage() : pageForActiveMap();
const mapSize = (map: MapDocument) => map.width * map.height;
const cellIndex = (map: MapDocument, point: CellPoint) => point.y * map.width + point.x;
const inside = (width: number, height: number, point: CellPoint) => point.x >= 0 && point.y >= 0 && point.x < width && point.y < height;
function frameSource(asset: PaletteAsset, frame: number): { x: number; y: number } { const column = frame % asset.columns, row = Math.floor(frame / asset.columns); return { x: asset.margin + column * (asset.tileSize + asset.spacing), y: asset.margin + row * (asset.tileSize + asset.spacing) }; }
function drawAsset(context: CanvasRenderingContext2D, assetId: string, frameNumber: number, dx: number, dy: number, size: number): void { const asset = catalogAsset(assetId), image = images.get(assetId); if (!asset || !image?.complete || image.naturalWidth === 0 || frameNumber < 0 || frameNumber >= asset.frameCount) { context.fillStyle = "#a94055"; context.fillRect(dx, dy, size, size); context.strokeStyle = "#ffd5db"; context.beginPath(); context.moveTo(dx, dy); context.lineTo(dx + size, dy + size); context.moveTo(dx + size, dy); context.lineTo(dx, dy + size); context.stroke(); return; } const source = frameSource(asset, frameNumber); context.drawImage(image, source.x, source.y, asset.tileSize, asset.tileSize, dx, dy, size, size); }
function selectedStamp() { const page = pageForEditor(); return page && paletteRect ? paletteStamp(page, paletteRect) : undefined; }
function sourceAsset(): PaletteAsset | undefined { return catalogAsset(selectedAssetId); }
function attributeSettings() { return { mode: "manual" as const, layer: layer.value as ManualLayer, collision: "unchanged" as const }; }
function historyFor(map: MapDocument) { let value = mapHistory.get(map.id); if (!value) { value = { undo: [], redo: [] }; mapHistory.set(map.id, value); } return value; }
function mapSnapshot(): MapDocument { if (!active) throw new Error("no active map"); return cloneMap(active); }
function syncComposite(map: MapDocument, index: number): void { const value = map.layers.decoration[index] ?? map.layers.structure[index] ?? map.layers.ground[index]; map.terrain[index] = value?.assetId ?? null; }
function syncAllComposite(map: MapDocument): void { for (let index = 0; index < mapSize(map); index += 1) syncComposite(map, index); }
function touch(map: MapDocument): void { map.updatedAt = new Date().toISOString(); }
async function saveActive(): Promise<void> { if (!active) return; maps = maps.map((map) => map.id === active!.id ? cloneMap(active!) : map); await repository.save(active); renderList(); }
function mutateMap(action: () => void): void { if (!active) return; const before = mapSnapshot(); action(); if (JSON.stringify(before) !== JSON.stringify(active)) { historyFor(active).undo.push(before); historyFor(active).redo = []; touch(active); void saveActive(); } render(); }
function selectPageForMap(): void { if (!active) return; activePageId = selectCompatiblePalettePageId(palettes.layout.pages, activePageId, active.tileSize); paletteRect = undefined; }
function selectPageForEditor(): void { if (editorMode !== "palette") return selectPageForMap(); if (!activePage()) activePageId = palettes.layout.pages.find((page) => page.mapKind === "dungeon" && page.tileSize === 16)?.id ?? palettes.layout.pages[0]?.id ?? ""; paletteRect = undefined; }
function ensurePalettePage(): PalettePage | undefined { let page = pageForEditor(); if (page) return page; const pageKind = active?.kind ?? "dungeon", pageTileSize = active?.tileSize ?? sourceAsset()?.tileSize ?? 16, id = uniqueId(`palette-${pageTileSize}`); palettes.mutate((layout) => addPalettePage(layout, createPalettePage({ id, label: `パレット ${pageTileSize}px`, mapKind: pageKind, tileSize: pageTileSize, width: 2048, height: 2048 }))); activePageId = id; page = activePage(); return page; }
function syncFloorControls(): void { const dungeon = mapKind.value === "dungeon"; floorField.hidden = !dungeon; applyFloorButton.hidden = !dungeon || active?.kind !== "dungeon"; if (!dungeon) return; const count = maps.filter((map) => map.kind === "dungeon").length; mapFloor.max = String(Math.max(1, count)); mapFloor.value = String(active?.kind === "dungeon" ? active.floor : Math.max(1, count + 1)); }
function setActive(map: MapDocument): void { active = cloneMap(map); kind.value = active.kind; mapKind.value = active.kind; mapFloor.value = String(active.floor); mapWidth.value = String(active.width); mapHeight.value = String(active.height); tileSize.value = String(active.tileSize); syncFloorControls(); selectPageForEditor(); updateMarkerOptions(); render(); }
function missingAssetIds(map: MapDocument): string[] { const values = new Set<string>(); for (const currentLayer of layers) for (const cell of map.layers[currentLayer]) if (cell && !assetById.has(cell.assetId)) values.add(cell.assetId); for (const entry of map.markers) if (entry.visual && !assetById.has(entry.visual.assetId)) values.add(entry.visual.assetId); return [...values]; }
function updateMarkerOptions(): void { if (!active) return; const kinds = active.kind === "home" ? homeMarkers : dungeonMarkers; const labels: Record<MapMarkerKind, string> = { homeSpawn: "開始位置", dungeonEntrance: "ダンジョン入口", homeStorage: "旧・保管位置", homePreparation: "探索準備", homeVisitors: "客の入口", shopkeeperCounter: "店主カウンター", customerCounter: "客カウンター", stairsUp: "上り階段", stairsDown: "下り階段" }; marker.innerHTML = kinds.map((value) => `<option value="${value}">${labels[value]} (${value})</option>`).join(""); }
function escapeHtml(value: string): string { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }
function renderList(): void { if (!active) return; const filtered = maps.filter((map) => map.kind === kind.value).sort((a, b) => a.floor - b.floor); mapCount.textContent = `${filtered.length} 枚`; mapList.innerHTML = filtered.map((map) => `<button class="map-list-item${map.id === active?.id ? " active" : ""}" data-map-id="${map.id}"><span>${escapeHtml(map.name)}</span><small>${map.kind === "home" ? "家" : `地下${map.floor}階`} / ${map.width}×${map.height} / ${map.tileSize}px</small></button>`).join("") || `<p class="small">この種類のマップはありません。</p>`; mapList.querySelectorAll<HTMLButtonElement>("[data-map-id]").forEach((button) => button.onclick = () => { const map = maps.find((value) => value.id === button.dataset.mapId); if (map) setActive(map); }); }
function renderPaletteTabs(): void {
  const current = active;
  const compatible = editorMode === "palette" ? palettes.layout.pages : current ? palettes.layout.pages.filter((page) => page.tileSize === current.tileSize) : [];
  paletteTabs.innerHTML = compatible.map((page) => `<button type="button" role="option" aria-selected="${page.id === activePageId}" data-page-id="${escapeHtml(page.id)}" class="palette-page-card${page.id === activePageId ? " active" : ""}"><span>${escapeHtml(page.label)}</span><small>${page.tileSize}px / ${page.width}×${page.height}</small></button>`).join("") || `<p class="small">${active ? `${active.tileSize}px のページがありません。` : "パレットがありません。"}</p>`;
  paletteTabs.querySelectorAll<HTMLButtonElement>("[data-page-id]").forEach((button) => button.onclick = () => { activePageId = button.dataset.pageId!; paletteRect = undefined; render(); });
  paletteDirty.textContent = palettes.dirty ? "未保存" : "保存済み";
  renderTagSummary();
  paletteSaveButton.disabled = !palettes.dirty;
}
function renderAssetOptions(): void {
  const search = assetSearchQuery.trim().toLocaleLowerCase();
  const requestedSize = assetSizeFilter === "all" ? undefined : Number(assetSizeFilter);
  const matchingSize = requestedSize ? assets.filter((asset) => asset.tileSize === requestedSize) : assets;
  const allowed = search ? matchingSize.filter((asset) => `${asset.label} ${asset.id}`.toLocaleLowerCase().includes(search)) : matchingSize;
  if (!allowed.some((asset) => asset.id === selectedAssetId)) selectedAssetId = allowed[0]?.id ?? "";
  assetSelect.innerHTML = allowed.map((asset) => `<option value="${escapeHtml(asset.id)}">${escapeHtml(asset.label)}</option>`).join(""); assetSelect.value = selectedAssetId;
  assetFolderStatus.textContent = `${allowed.length} / ${assets.length}枚`;
  assetPicker.innerHTML = allowed.map((asset) => `<button type="button" class="asset-image-card${asset.id === selectedAssetId ? " active" : ""}" data-asset-card="${escapeHtml(asset.id)}" title="${escapeHtml(asset.label)}"><img class="asset-image-thumbnail" src="${escapeHtml(asset.path)}" alt="" loading="lazy"><span>${escapeHtml(asset.label)}</span><small>${asset.tileSize}px / ${asset.columns}×${asset.rows}</small></button>`).join("") || `<p class="small">この条件に合う素材がありません。サイズを「すべて」にするか検索を消してください。</p>`;
  assetPicker.querySelectorAll<HTMLButtonElement>("[data-asset-card]").forEach((button) => button.onclick = () => { selectedAssetId = button.dataset.assetCard!; sessionStorage.setItem(selectedAssetStorageKey, selectedAssetId); assetSelect.value = selectedAssetId; sourceRect = undefined; renderAssetOptions(); renderSource(); });
  if (revealSelectedAsset) {
    revealSelectedAsset = false;
    const selectedCard = assetPicker.querySelector<HTMLElement>(`[data-asset-card="${CSS.escape(selectedAssetId)}"]`);
    window.requestAnimationFrame(() => selectedCard?.scrollIntoView({ block: "center" }));
  }
}

async function loadAssetCatalog(preferredAssetId?: string): Promise<void> {
  try {
    const response = await fetch(`/assets/map-tiles/generated/catalog.json?editor=${Date.now()}`, { cache: "no-store", headers: { Accept: "application/json" } });
    if (!response.ok) throw new Error("asset catalog endpoint unavailable");
    const incoming = await response.json() as { assets?: PaletteAsset[] };
    if (!Array.isArray(incoming.assets)) throw new Error("asset catalog is invalid");
    assets = incoming.assets.map((asset) => ({ ...asset, mapKinds: [...asset.mapKinds] }));
    assetById = new Map(assets.map((asset) => [asset.id, asset]));
    for (const id of [...images.keys()]) if (!assetById.has(id)) images.delete(id);
    for (const asset of assets) {
      const current = images.get(asset.id);
      if (current?.src.endsWith(asset.path)) continue;
      const image = new Image(); image.onload = () => render(); image.src = asset.path; images.set(asset.id, image);
    }
    const requested = preferredAssetId ?? sessionStorage.getItem(selectedAssetStorageKey) ?? selectedAssetId;
    if (requested && assetById.has(requested)) { selectedAssetId = requested; sessionStorage.setItem(selectedAssetStorageKey, requested); }
    revealSelectedAsset = true;
  } catch (error) {
    status.textContent = `素材一覧の再読込エラー: ${error instanceof Error ? error.message : "不明"}`;
  }
}
function renderEnemyRoster(): void {
  if (!active || active.kind !== "dungeon") { enemyRoster.innerHTML = `<p class="small">家では敵ロスターを使用しません。</p>`; enemyRosterStatus.textContent = ""; return; }
  const actors = Object.values(ACTOR_CATALOG).filter((actor) => actor.roles?.includes("enemy") && actorHasEnemyStats(actor) && actorSupportsDirectionalMovement(actor));
  enemyRoster.innerHTML = actors.length ? actors.map((actor) => {
    const stats = actorEnemyStatsAt(actor, 1)!;
    return `<label class="enemy-roster-item"><input type="checkbox" data-enemy-id="${escapeHtml(actor.id)}" ${active!.enemyRoster.includes(actor.id) ? "checked" : ""}><span>${escapeHtml(actor.label)}</span><small>B1 HP ${stats.maxHp} / 攻撃 ${stats.damage}</small></label>`;
  }).join("") : `<p class="small">敵アクターが登録されていません。</p>`;
  enemyRosterStatus.textContent = `${active.enemyRoster.length}体候補を選択中（0件なら敵なし）`;
  enemyRoster.querySelectorAll<HTMLInputElement>("[data-enemy-id]").forEach((input) => input.onchange = () => mutateMap(() => {
    const id = input.dataset.enemyId!;
    active!.enemyRoster = input.checked ? [...new Set([...active!.enemyRoster, id])] : active!.enemyRoster.filter((value) => value !== id);
  }));
}
function actorPreviewClip(actor: CraftpixActorDefinition): CraftpixActorClip | undefined { return (actor.clips.idle ?? actor.clips.walk ?? actor.clips.attack ?? Object.values(actor.clips)[0]) as CraftpixActorClip | undefined; }
function drawActorThumbnail(canvas: HTMLCanvasElement, actor: CraftpixActorDefinition): void {
  const context = canvas.getContext("2d"); if (!context) return;
  context.imageSmoothingEnabled = false; context.fillStyle = "#101725"; context.fillRect(0, 0, canvas.width, canvas.height);
  for (let y = 0; y < canvas.height; y += 12) for (let x = 0; x < canvas.width; x += 12) { context.fillStyle = ((x + y) / 12) % 2 ? "#182233" : "#1d2a3e"; context.fillRect(x, y, 12, 12); }
  const clip = actorPreviewClip(actor); if (!clip) return;
  const image = previewImage(clip); if (!image.complete || image.naturalWidth === 0) return;
  const rect = actorPreviewFrameRect(clip, clip.directions[0] ?? "down", 0), scale = Math.max(1, Math.floor(Math.min((canvas.width - 8) / rect.width, (canvas.height - 8) / rect.height))), width = rect.width * scale, height = rect.height * scale;
  context.drawImage(image, rect.sx, rect.sy, rect.width, rect.height, Math.floor((canvas.width - width) / 2), Math.floor((canvas.height - height) / 2), width, height);
}
function renderMapActorStrip(): void {
  if (!active || active.kind !== "dungeon") { paletteActorStrip.hidden = true; paletteActorStripList.innerHTML = ""; paletteActorStripStatus.textContent = ""; return; }
  paletteActorStrip.hidden = false;
  const actors = Object.values(ACTOR_CATALOG).filter((actor) => actor.roles?.includes("enemy") && actorHasEnemyStats(actor) && actorSupportsDirectionalMovement(actor)).sort((a, b) => a.label.localeCompare(b.label));
  paletteActorStripStatus.textContent = `${active.enemyRoster.length}体候補を選択中`;
  paletteActorStripList.innerHTML = actors.map((actor) => {
    const selected = active!.enemyRoster.includes(actor.id);
    const control = `<input type="checkbox" data-strip-actor-id="${escapeHtml(actor.id)}" ${selected ? "checked" : ""}>`;
    const remove = selected ? `<button type="button" class="actor-strip-remove" data-remove-strip-actor="${escapeHtml(actor.id)}" aria-label="${escapeHtml(actor.label)}をこのマップから削除">削除</button>` : "";
    return `<label class="actor-strip-card${selected ? " selected" : ""}">${control}<canvas data-strip-actor-thumb="${escapeHtml(actor.id)}" width="58" height="58"></canvas><span>${escapeHtml(actor.label)}</span><small>HP ${actorEnemyStatsAt(actor, 1)?.maxHp ?? "?"}</small>${remove}</label>`;
  }).join("") || `<p class="small">登録済みのキャラクターがありません。</p>`;
  actors.forEach((actor) => { const canvas = paletteActorStripList.querySelector<HTMLCanvasElement>(`[data-strip-actor-thumb="${CSS.escape(actor.id)}"]`); if (canvas) drawActorThumbnail(canvas, actor); });
  paletteActorStripList.querySelectorAll<HTMLInputElement>("[data-strip-actor-id]").forEach((input) => input.onchange = () => mutateMap(() => { const id = input.dataset.stripActorId!; active!.enemyRoster = input.checked ? [...new Set([...active!.enemyRoster, id])] : active!.enemyRoster.filter((value) => value !== id); }));
  paletteActorStripList.querySelectorAll<HTMLButtonElement>("[data-remove-strip-actor]").forEach((button) => button.onclick = (event) => { event.preventDefault(); event.stopPropagation(); mutateMap(() => { active!.enemyRoster = active!.enemyRoster.filter((id) => id !== button.dataset.removeStripActor); }); });
}
function selectedPreviewActor() { return ACTOR_CATALOG[actorPreviewId.value] ?? Object.values(ACTOR_CATALOG)[0]; }
function previewImage(clip: CraftpixActorClip): HTMLImageElement {
  const path = actorPreviewPath(clip.path);
  let image = actorPreviewImages.get(path);
  if (!image) { image = new Image(); image.onload = () => { drawActorPreview(); renderActorPreviewOptions(); renderMapActorStrip(); }; image.onerror = () => { drawActorPreview(); renderActorPreviewOptions(); renderMapActorStrip(); }; image.src = path; actorPreviewImages.set(path, image); }
  return image;
}
function renderActorPreviewOptions(): void {
  const actors = Object.values(ACTOR_CATALOG).sort((a, b) => a.label.localeCompare(b.label));
  actorLibraryCount.textContent = `${actors.length}体`;
  if (!actors.length) { actorPreviewId.innerHTML = `<option value="">登録なし</option>`; actorPreviewAction.innerHTML = ""; actorPreviewDirection.innerHTML = ""; actorPreviewList.innerHTML = `<p class="small">アクターが登録されていません。</p>`; actorSettings.innerHTML = `<p class="small">アクターが登録されていません。</p>`; return; }
  const previousId = actorPreviewId.value;
  actorPreviewId.innerHTML = actors.map((actor) => `<option value="${escapeHtml(actor.id)}">${escapeHtml(actor.label)}</option>`).join("");
  actorPreviewId.value = actors.some((actor) => actor.id === previousId) ? previousId : actors[0]!.id;
  actorPreviewList.innerHTML = actors.map((actor) => `<button type="button" class="actor-preview-card${actor.id === actorPreviewId.value ? " active" : ""}" data-actor-card="${escapeHtml(actor.id)}"><canvas data-actor-card-thumb="${escapeHtml(actor.id)}" width="82" height="82"></canvas><strong>${escapeHtml(actor.label)}</strong><small>${actor.roles?.includes("enemy") ? "敵" : actor.roles?.includes("player") ? "プレイヤー" : "NPC"}</small></button>`).join("");
  actors.forEach((actor) => { const canvas = actorPreviewList.querySelector<HTMLCanvasElement>(`[data-actor-card-thumb="${CSS.escape(actor.id)}"]`); if (canvas) drawActorThumbnail(canvas, actor); });
  actorPreviewList.querySelectorAll<HTMLButtonElement>("[data-actor-card]").forEach((button) => button.onclick = () => { actorPreviewId.value = button.dataset.actorCard!; actorPreviewState = { action: "idle", direction: "down", frame: 0, elapsedMs: 0 }; renderActorPreviewOptions(); drawActorPreview(); });
  const actor = selectedPreviewActor(), actions = actorPreviewActions(actor);
  if (!actions.includes(actorPreviewState.action)) actorPreviewState = { ...actorPreviewState, action: actions[0] ?? "idle", frame: 0, elapsedMs: 0 };
  actorPreviewAction.innerHTML = actions.map((action) => `<option value="${escapeHtml(action)}">${escapeHtml(action)}</option>`).join("");
  actorPreviewAction.value = actorPreviewState.action;
  const clip = actor?.clips[actorPreviewState.action as keyof typeof actor.clips], directions = actorPreviewDirections(clip);
  if (!directions.includes(actorPreviewState.direction)) actorPreviewState = { ...actorPreviewState, direction: directions[0] ?? "down", frame: 0, elapsedMs: 0 };
  actorPreviewDirection.innerHTML = directions.map((direction) => `<option value="${direction}">${direction}</option>`).join("");
  actorPreviewDirection.value = actorPreviewState.direction;
  renderActorSettingsForm();
}
function renderActorSettingsForm(): void {
  const actor = selectedPreviewActor();
  if (!actor) { actorSettings.innerHTML = ""; return; }
  const stored = loadedActorSettings.actors[actor.id] ?? {}, roles = stored.roles ?? actor.roles ?? [];
  const archetype = stored.archetype ?? actor.archetype ?? "brute";
  const tier = stored.tier ?? actor.tier ?? 1;
  // The author picks what a creature is, not what its numbers are. The table
  // below shows what the shared curve makes of that choice.
  const preview = actorStatPreviewRows(archetype, tier);
  actorSettings.innerHTML = `<label class="actor-setting-field">表示名 <input data-actor-label value="${escapeHtml(stored.label ?? actor.label)}"></label><div class="actor-role-fields"><span>役割</span><label><input type="checkbox" data-actor-role="enemy" ${roles.includes("enemy") ? "checked" : ""}>敵</label><label><input type="checkbox" data-actor-role="npc" ${roles.includes("npc") ? "checked" : ""}>NPC</label><label><input type="checkbox" data-actor-role="player" ${roles.includes("player") ? "checked" : ""}>プレイヤー</label></div><div class="actor-stat-fields"><label>系統 <select data-actor-archetype>${ACTOR_ARCHETYPES.map((value) => `<option value="${value}"${value === archetype ? " selected" : ""}>${ARCHETYPE_LABELS[value]}</option>`).join("")}</select></label><label>格 <select data-actor-tier>${ACTOR_TIERS.map((value) => `<option value="${value}"${value === tier ? " selected" : ""}>ティア${value}</option>`).join("")}</select></label></div><table class="actor-stat-preview"><caption>この設定での能力値</caption><thead><tr><th>階</th><th>HP</th><th>攻撃</th></tr></thead><tbody data-actor-stat-preview>${preview}</tbody></table>`;
  for (const control of actorSettings.querySelectorAll<HTMLSelectElement>("[data-actor-archetype], [data-actor-tier]")) {
    // Refresh only the table: rebuilding the form would read the stored values
    // back and discard the choice that was just made.
    control.onchange = () => renderActorStatPreview();
  }
}
function actorStatPreviewRows(archetype: ActorArchetype, tier: ActorTier): string {
  return [1, 5, 10].map((floor) => { const stats = enemyStatsAt({ archetype, tier }, floor); return `<tr><th>B${floor}</th><td>${stats.maxHp}</td><td>${stats.damage}</td></tr>`; }).join("");
}
function renderActorStatPreview(): void {
  const body = actorSettings.querySelector("[data-actor-stat-preview]");
  const archetype = actorSettings.querySelector<HTMLSelectElement>("[data-actor-archetype]")?.value as ActorArchetype | undefined;
  const tier = Number(actorSettings.querySelector<HTMLSelectElement>("[data-actor-tier]")?.value ?? 1) as ActorTier;
  if (body && archetype) body.innerHTML = actorStatPreviewRows(archetype, tier);
}
function drawActorPreview(): void {
  actorPreviewContext.imageSmoothingEnabled = false;
  actorPreviewContext.fillStyle = "#101725"; actorPreviewContext.fillRect(0, 0, actorPreviewCanvas.width, actorPreviewCanvas.height);
  for (let y = 0; y < actorPreviewCanvas.height; y += 16) for (let x = 0; x < actorPreviewCanvas.width; x += 16) { actorPreviewContext.fillStyle = ((x + y) / 16) % 2 ? "#182233" : "#1d2a3e"; actorPreviewContext.fillRect(x, y, 16, 16); }
  const actor = selectedPreviewActor(), clip = actor?.clips[actorPreviewState.action as keyof typeof actor.clips];
  if (!actor || !clip) { actorPreviewStatus.textContent = "表示できるアニメーションがありません。"; return; }
  const image = previewImage(clip);
  if (!image.complete || image.naturalWidth === 0) { actorPreviewStatus.textContent = `${actor.label} / ${actorPreviewState.action} を読み込み中…`; return; }
  const rect = actorPreviewFrameRect(clip, actorPreviewState.direction, actorPreviewState.frame), maxSize = 154, scale = Math.max(1, Math.floor(maxSize / Math.max(rect.width, rect.height))), width = rect.width * scale, height = rect.height * scale, dx = Math.floor((actorPreviewCanvas.width - width) / 2), dy = Math.floor((actorPreviewCanvas.height - height) / 2);
  actorPreviewContext.drawImage(image, rect.sx, rect.sy, rect.width, rect.height, dx, dy, width, height);
  const derived = actorEnemyStatsAt(actor, 1);
  const stats = derived ? ` / B1 HP ${derived.maxHp} / 攻撃 ${derived.damage}` : "";
  actorPreviewStatus.textContent = `${actor.label} / ${actorPreviewState.action} / ${actorPreviewState.direction} / frame ${actorPreviewState.frame + 1}/${clip.columns}${stats}`;
}
function animateActorPreview(time: number): void {
  const delta = actorPreviewLastTime ? Math.min(100, time - actorPreviewLastTime) : 0; actorPreviewLastTime = time;
  const actor = selectedPreviewActor(), clip = actor?.clips[actorPreviewState.action as keyof typeof actor.clips];
  if (clip) actorPreviewState = advanceActorPreview(actorPreviewState, clip, delta);
  drawActorPreview(); window.requestAnimationFrame(animateActorPreview);
}
async function loadActorSettings(): Promise<void> {
  if (import.meta.env.DEV) {
    try { const response = await fetch("/__map-editor/actors/settings", { headers: { Accept: "application/json" } }); if (response.ok) loadedActorSettings = await response.json() as ActorSettingsCatalog; } catch { /* use generated settings */ }
  }
  applyActorSettings(loadedActorSettings); renderActorPreviewOptions(); renderEnemyRoster();
}
async function saveActorSettings(): Promise<void> {
  const actor = selectedPreviewActor(); if (!actor) return;
  const roles = (["enemy", "npc", "player"] as const).filter((role) => actorSettings.querySelector<HTMLInputElement>(`[data-actor-role="${role}"]`)?.checked === true);
  // Only identity is stored; the numbers stay in src/game/dungeonDifficulty.ts.
  const next: ActorSettingsCatalog = { version: 1, actors: { ...loadedActorSettings.actors, [actor.id]: { label: actorSettings.querySelector<HTMLInputElement>("[data-actor-label]")?.value.trim() || actor.label, roles, archetype: actorSettings.querySelector<HTMLSelectElement>("[data-actor-archetype]")?.value as ActorArchetype, tier: Number(actorSettings.querySelector<HTMLSelectElement>("[data-actor-tier]")?.value ?? 1) as ActorTier } } };
  try {
    if (import.meta.env.DEV) { const response = await fetch("/__map-editor/actors/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }); if (!response.ok) throw new Error(await response.text()); loadedActorSettings = await response.json().then((body) => body.settings as ActorSettingsCatalog); }
    else { download("actor-settings.json", next); loadedActorSettings = next; }
    applyActorSettings(loadedActorSettings); renderActorPreviewOptions(); renderEnemyRoster(); actorSettingsStatus.textContent = "キャラクター設定を保存しました。";
  } catch (error) { actorSettingsStatus.textContent = `キャラクター設定保存エラー: ${error instanceof Error ? error.message : "不明"}`; }
}
/** How each detected sheet shape is described in the import review. */
const IMPORT_FORMATS: Record<string, { label: string; hint: string }> = {
  "wolf-autotile": { label: "オートタイル", hint: "ウディタの5部品を47タイルへ展開して登録します。プレビューで形を確認してください。" },
  "section-catalog": { label: "カタログ区分", hint: "見出し帯で区切られた区画です。帯の画像を見て名前を付けてください。" },
  grid: { label: "通常グリッド", hint: "セルサイズを確認してから登録します。" },
  unknown: { label: "形式不明", hint: "既知の形式に一致しません。セルサイズを手動指定するか、登録から外してください。" },
};

function importRow(entry: any): string {
  const id = escapeHtml(entry.id);
  const kind = entry.format?.kind ?? "grid";
  const geometry = `${entry.tileSize ?? "?"}px / ${entry.columns ?? "?"}×${entry.rows ?? "?"} = ${entry.frameCount ?? "?"}フレーム`;
  // Geometry is derived for autotiles and catalogue sections, so only a plain
  // grid or an unrecognised sheet still needs the manual controls.
  const editable = kind === "grid" || kind === "unknown";
  const controls = editable
    ? `<label>セル <select data-import-tile-size="${id}"><option value="">手動</option><option value="16" ${entry.tileSize === 16 ? "selected" : ""}>16px</option><option value="32" ${entry.tileSize === 32 ? "selected" : ""}>32px</option></select></label><label>余白 <input type="number" min="0" data-import-margin="${id}" value="${Number(entry.margin ?? 0)}"></label><label>間隔 <input type="number" min="0" data-import-spacing="${id}" value="${Number(entry.spacing ?? 0)}"></label>`
    : "";
  const detail = kind === "wolf-autotile" ? `47タイル × ${entry.autotile?.animationFrames ?? 1}コマ`
    : kind === "section-catalog" ? `${entry.section?.fromRow}〜${entry.section?.toRow}行`
    : geometry;
  const preview = entry.preview ? `<img class="import-preview" src="${escapeHtml(entry.preview)}" alt="">` : "";
  const warnings = entry.warnings?.length ? `<small class="import-warning">${escapeHtml(entry.warnings.join(" / "))}</small>` : "";
  return `<div class="import-row import-row-${escapeHtml(kind)}">
    <label class="import-pick"><input type="checkbox" data-import-map-id="${id}" ${entry.selected ? "checked" : ""}></label>
    ${preview}
    <div class="import-main"><input class="import-label" data-import-label="${id}" value="${escapeHtml(entry.label)}" aria-label="${id} の名前"><small>${escapeHtml(detail)} · ${escapeHtml(entry.sourcePath ?? "")}</small>${warnings}</div>
    <div class="import-controls">${controls}</div>
  </div>`;
}

function importGroup(kind: string, entries: any[]): string {
  if (!entries.length) return "";
  const meta = IMPORT_FORMATS[kind] ?? IMPORT_FORMATS.grid!;
  // Anything needing a decision opens by itself: unrecognised sheets, sections
  // waiting to be named, and any candidate the importer flagged. Long confident
  // groups stay shut so the list is readable.
  const open = kind === "unknown" || kind === "section-catalog" || entries.some((entry) => entry.warnings?.length) || entries.length <= 12;
  return `<details class="import-group" ${open ? "open" : ""}>
    <summary><strong>${escapeHtml(meta.label)}</strong> <span>${entries.length}件</span><button type="button" data-import-group-toggle="${escapeHtml(kind)}">この分類を全選択／全解除</button></summary>
    <p class="small">${escapeHtml(meta.hint)}</p>
    ${entries.map(importRow).join("")}
  </details>`;
}

function renderImportReport(): void {
  if (!pendingImport) { importReport.innerHTML = ""; return; }
  const analysis = pendingImport.analysis;
  const candidates: any[] = analysis.mapTiles ?? [];
  const byKind = new Map<string, any[]>();
  for (const entry of candidates) {
    const kind = entry.format?.kind ?? "grid";
    if (!byKind.has(kind)) byKind.set(kind, []);
    byKind.get(kind)!.push(entry);
  }
  const mapRows = ["unknown", "section-catalog", "wolf-autotile", "grid"].map((kind) => importGroup(kind, byKind.get(kind) ?? [])).join("");
  const groups: any[] = analysis.tileGroups ?? [];
  const groupPanel = groups.length
    ? `<div class="import-tile-groups"><h3>取込元のタイルセット構成</h3><p class="small">素材集の作者が付けた分類です。ダンジョンテーマを組むときの下書きとして使えます。</p>${groups.map((group) => `<div class="import-tile-group"><strong>${escapeHtml(group.label)}</strong><small>${escapeHtml(group.images.map((image: string) => image.split("/").pop()).join(", "))}</small></div>`).join("")}</div>`
    : "";
  const actorRows = (analysis.actors ?? []).map((entry: any) => `<div class="import-actor"><label><input type="checkbox" data-import-actor-id="${escapeHtml(entry.id)}" checked><span>${escapeHtml(entry.label)}</span></label><label>HP <input type="number" min="1" data-import-hp="${escapeHtml(entry.id)}" value="3"></label><label>階加算 <input type="number" min="0" data-import-hp-floor="${escapeHtml(entry.id)}" value="1"></label><label>攻撃 <input type="number" min="0" data-import-damage="${escapeHtml(entry.id)}" value="1"></label><small>action: ${escapeHtml(Object.keys(entry.clips ?? {}).join(", "))}</small></div>`).join("");
  const summary = [...byKind.entries()].map(([kind, entries]) => `${IMPORT_FORMATS[kind]?.label ?? kind} ${entries.length}`).join(" / ");
  importReport.innerHTML = `<p class="small">${escapeHtml(analysis.source.fileName)} — マップ素材 ${candidates.length}件（${escapeHtml(summary)}） / キャラクター ${analysis.actors?.length ?? 0}件</p><p class="small">マップ素材: assets-src/map-tiles/sheets/imported/　キャラクター: assets-src/actors/imported/</p>${groupPanel}<div class="import-list">${mapRows || `<p class="small">マップ素材候補なし</p>`}${actorRows ? `<details class="import-group" open><summary><strong>キャラクター</strong> <span>${analysis.actors.length}件</span></summary>${actorRows}</details>` : `<p class="small">アクター候補なし</p>`}</div><label class="small"><input type="checkbox" data-import-pages checked>選択したマップ素材からパレットページを自動作成（推奨）</label><label class="small"><input type="checkbox" data-import-license>利用条件／ライセンスを確認しました</label><div class="import-actions"><button data-action="import-select-all">全候補を選択</button><button data-action="import-commit">まとめて登録</button><button data-action="import-cancel">キャンセル</button></div>`;
  q<HTMLButtonElement>("[data-action=import-select-all]").onclick = () => { importReport.querySelectorAll<HTMLInputElement>("[data-import-map-id], [data-import-actor-id]").forEach((input) => { input.checked = true; }); status.textContent = "全候補を選択しました。セルサイズと利用条件を確認してから、まとめて登録してください。"; };
  for (const button of importReport.querySelectorAll<HTMLButtonElement>("[data-import-group-toggle]")) {
    button.onclick = (event) => {
      event.preventDefault();
      const inputs = [...(button.closest("details")?.querySelectorAll<HTMLInputElement>("[data-import-map-id]") ?? [])];
      const next = !inputs.every((input) => input.checked);
      for (const input of inputs) input.checked = next;
    };
  }
  q<HTMLButtonElement>("[data-action=import-cancel]").onclick = () => { pendingImport = undefined; renderImportReport(); };
  q<HTMLButtonElement>("[data-action=import-commit]").onclick = async () => {
    const licenseAcknowledged = importReport.querySelector<HTMLInputElement>("[data-import-license]")?.checked === true;
    if (!licenseAcknowledged) { status.textContent = "利用条件／ライセンスを確認してから登録してください。"; return; }
    const selectedAssetBeforeImport = sessionStorage.getItem(selectedAssetStorageKey);
    try {
      const mapTiles = (analysis.mapTiles ?? []).map((entry: any) => {
        const field = <T extends Element>(attribute: string) => importReport.querySelector<T>(`[${attribute}="${CSS.escape(entry.id)}"]`);
        const selected = field<HTMLInputElement>("data-import-map-id")?.checked ?? false;
        const label = field<HTMLInputElement>("data-import-label")?.value.trim() || entry.label;
        // Autotiles and catalogue sections carry geometry the importer derived;
        // only a plain grid exposes controls to override it.
        const sizeControl = field<HTMLSelectElement>("data-import-tile-size");
        const tileSize = sizeControl ? (sizeControl.value ? Number(sizeControl.value) : undefined) : entry.tileSize;
        const margin = sizeControl ? Number(field<HTMLInputElement>("data-import-margin")?.value ?? 0) : entry.margin ?? 0;
        const spacing = sizeControl ? Number(field<HTMLInputElement>("data-import-spacing")?.value ?? 0) : entry.spacing ?? 0;
        if (selected && !tileSize) throw new Error(`${label}: 16pxまたは32pxのセルサイズを選択してください`);
        return { ...entry, selected, label, tileSize, margin, spacing };
      });
      const actors = (analysis.actors ?? []).map((entry: any) => ({ ...entry, selected: importReport.querySelector<HTMLInputElement>(`[data-import-actor-id="${CSS.escape(entry.id)}"]`)?.checked ?? false, enemyStats: { baseHp: Number(importReport.querySelector<HTMLInputElement>(`[data-import-hp="${CSS.escape(entry.id)}"]`)?.value ?? 3), hpPerFloor: Number(importReport.querySelector<HTMLInputElement>(`[data-import-hp-floor="${CSS.escape(entry.id)}"]`)?.value ?? 1), damage: Number(importReport.querySelector<HTMLInputElement>(`[data-import-damage="${CSS.escape(entry.id)}"]`)?.value ?? 1) } }));
      const firstImportedAssetId = mapTiles.find((entry: any) => entry.selected)?.id as string | undefined;
      if (firstImportedAssetId) sessionStorage.setItem(selectedAssetStorageKey, firstImportedAssetId);
      const response = await fetch(`/__map-editor/import/${pendingImport!.id}/commit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mapTiles, actors, createPalettePages: importReport.querySelector<HTMLInputElement>("[data-import-pages]")?.checked === true, licenseAcknowledged }) }); if (!response.ok) throw new Error(await response.text()); status.textContent = "素材を登録しました。素材フォルダで画像を表示します。"; window.setTimeout(() => window.location.reload(), 250);
    } catch (error) { if (selectedAssetBeforeImport) sessionStorage.setItem(selectedAssetStorageKey, selectedAssetBeforeImport); else sessionStorage.removeItem(selectedAssetStorageKey); status.textContent = `素材登録エラー: ${error instanceof Error ? error.message : "不明"}`; }
  };
}
function drawSelection(context: CanvasRenderingContext2D, rect: CellRect, size: number, colour: string): void { context.lineWidth = 2; context.strokeStyle = colour; context.strokeRect(rect.x * size + 1, rect.y * size + 1, rect.width * size - 2, rect.height * size - 2); }
function renderSource(): void { const asset = sourceAsset(); if (!asset) { sourceCanvas.width = sourceCanvas.height = 1; return; } const fit = fitEditorCanvas(asset.columns, asset.rows, asset.tileSize * sourceScale); sourceCellPixels = fit.cellPixels; sourceCanvas.width = fit.width; sourceCanvas.height = fit.height; sourceContext.imageSmoothingEnabled = false; sourceContext.clearRect(0, 0, sourceCanvas.width, sourceCanvas.height); for (let frame = 0; frame < asset.frameCount; frame += 1) drawAsset(sourceContext, asset.id, frame, (frame % asset.columns) * sourceCellPixels, Math.floor(frame / asset.columns) * sourceCellPixels, sourceCellPixels); sourceContext.strokeStyle = "#ffffff33"; for (let x = 0; x <= asset.columns; x += 1) { sourceContext.beginPath(); sourceContext.moveTo(x * sourceCellPixels, 0); sourceContext.lineTo(x * sourceCellPixels, sourceCanvas.height); sourceContext.stroke(); } for (let y = 0; y <= asset.rows; y += 1) { sourceContext.beginPath(); sourceContext.moveTo(0, y * sourceCellPixels); sourceContext.lineTo(sourceCanvas.width, y * sourceCellPixels); sourceContext.stroke(); } if (sourceRect) drawSelection(sourceContext, sourceRect, sourceCellPixels, "#ffd166"); }
const TAG_ROLE_INK: Record<PaletteCellRole, string> = { floor: "#5fa8d3", wall: "#c8922e", prop: "#8fbf6a", stairs: "#c46fd0", liquid: "#3fc0b0" };

/**
 * Marks triage state on the palette itself: a corner pip for the role and a
 * wash over anything rejected, so a shelf's state reads without clicking.
 */
function drawPaletteTags(page: PalettePage, columns: number, rows: number): void {
  const pip = Math.max(2, Math.round(paletteCellPixels / 5));
  for (const cell of page.cells) {
    if (cell.x >= columns || cell.y >= rows) continue;
    const x = cell.x * paletteCellPixels, y = cell.y * paletteCellPixels;
    if (cell.status === "rejected") {
      paletteContext.fillStyle = "#0b0f16b0";
      paletteContext.fillRect(x, y, paletteCellPixels, paletteCellPixels);
    }
    if (!cell.role) continue;
    paletteContext.fillStyle = TAG_ROLE_INK[cell.role];
    paletteContext.fillRect(x + paletteCellPixels - pip - 1, y + 1, pip, pip);
  }
}

/** Keeps the triage backlog visible: what is left to sort is the real progress bar. */
function renderTagSummary(): void {
  const page = pageForEditor();
  const summary = paletteTagSummary(page ? [page] : []);
  if (!page || summary.cells === 0) { tagSummary.textContent = "このページにタイルはありません。"; return; }
  const roles = (["floor", "wall", "prop", "stairs", "liquid"] as const)
    .map((role) => ({ role, count: summary.byRole[role] })).filter((entry) => entry.count > 0)
    .map((entry) => `${TAG_ROLE_LABELS[entry.role]} ${entry.count}`).join(" / ");
  const rejected = summary.byStatus.rejected ? `・不採用 ${summary.byStatus.rejected}` : "";
  tagSummary.textContent = `${summary.cells}枚中 未仕分け ${summary.untagged}${roles ? `・${roles}` : ""}${rejected}`;
}

function renderPalette(): void { const page = pageForEditor(); if (!page) { paletteRenderedColumns = paletteRenderedRows = 1; paletteCanvas.width = paletteCanvas.height = 1; paletteCanvas.style.width = "1px"; paletteCanvas.style.height = "1px"; return; } const requested = page.tileSize * sourceScale, extent = sparseGridExtent(page.width, page.height, page.cells, paletteRect); paletteRenderedColumns = extent.columns; paletteRenderedRows = extent.rows; const fit = fitEditorCanvas(extent.columns, extent.rows, requested); paletteCellPixels = fit.cellPixels; paletteCanvas.width = fit.width; paletteCanvas.height = fit.height; const displayScale = requested / paletteCellPixels; paletteCanvas.style.width = `${Math.ceil(fit.width * displayScale)}px`; paletteCanvas.style.height = `${Math.ceil(fit.height * displayScale)}px`; paletteContext.imageSmoothingEnabled = false; paletteContext.fillStyle = "#101725"; paletteContext.fillRect(0, 0, paletteCanvas.width, paletteCanvas.height); for (const cell of page.cells) if (cell.x < extent.columns && cell.y < extent.rows) drawAsset(paletteContext, cell.assetId, cell.frame, cell.x * paletteCellPixels, cell.y * paletteCellPixels, paletteCellPixels); drawPaletteTags(page, extent.columns, extent.rows); paletteContext.strokeStyle = "#ffffff20"; for (let x = 0; x <= extent.columns; x += 1) { paletteContext.beginPath(); paletteContext.moveTo(x * paletteCellPixels, 0); paletteContext.lineTo(x * paletteCellPixels, paletteCanvas.height); paletteContext.stroke(); } for (let y = 0; y <= extent.rows; y += 1) { paletteContext.beginPath(); paletteContext.moveTo(0, y * paletteCellPixels); paletteContext.lineTo(paletteCanvas.width, y * paletteCellPixels); paletteContext.stroke(); } if (paletteRect) drawSelection(paletteContext, paletteRect, paletteCellPixels, "#70d9ce"); }
function drawMapCell(map: MapDocument, index: number, x: number, y: number, display: number): void { const px = x * display, py = y * display; mapContext.fillStyle = "#172130"; mapContext.fillRect(px, py, display, display); for (const currentLayer of layers) { if (layerVisibility.get(currentLayer)?.checked === false) continue; const cell = map.layers[currentLayer][index]; if (cell) drawAsset(mapContext, cell.assetId, cell.frame, px, py, display); } if (pass.checked) { mapContext.fillStyle = map.collision[index] ? "#00c8f08f" : "#ff4b1fa6"; mapContext.fillRect(px, py, display, display); } if (grid.checked) { mapContext.strokeStyle = "#ffffff38"; mapContext.strokeRect(px, py, display, display); } }
function drawMarker(entry: MapMarker, display: number): void { const px = entry.x * display, py = entry.y * display; if (entry.visual) drawAsset(mapContext, entry.visual.assetId, entry.visual.frame, px, py, display); mapContext.fillStyle = entry.visual ? "#ffd166bb" : "#ffd166"; mapContext.fillRect(px + display * .25, py + display * .25, display * .5, display * .5); mapContext.fillStyle = "#fff8d7"; mapContext.font = `${Math.max(8, display * .55)}px sans-serif`; mapContext.fillText(entry.kind, px + 2, py + Math.max(10, display * .75)); }
function renderMap(): void { if (!active) return; const requested = active.tileSize * Number(zoom.value), fit = fitEditorCanvas(active.width, active.height, requested); mapCellPixels = fit.cellPixels; mapCanvas.width = fit.width; mapCanvas.height = fit.height; mapContext.imageSmoothingEnabled = false; mapContext.clearRect(0, 0, mapCanvas.width, mapCanvas.height); for (let y = 0; y < active.height; y += 1) for (let x = 0; x < active.width; x += 1) drawMapCell(active, y * active.width + x, x, y, mapCellPixels); for (const entry of active.markers) drawMarker(entry, mapCellPixels); mapTitle.textContent = `${active.name}${active.kind === "dungeon" ? `（地下${active.floor}階）` : ""} — ${active.width}×${active.height} / ${active.tileSize}px`; const stamp = selectedStamp(); stampInfo.textContent = stamp ? `${stamp.width}×${stamp.height} スタンプ` : "スタンプ未選択"; canvasFitWarning.hidden = !fit.reduced; canvasFitWarning.textContent = fit.reduced ? `大きなマップのため表示を ${mapCellPixels}px/セルへ自動縮小しています（指定: ${requested}px/セル）。編集座標は保持されます。` : ""; }
function describeValidationIssue(issue: string): string {
  const marker = issue.match(/^marker (\w+)(?: visual)?$/);
  if (marker) return `必須マーカー「${marker[1]}」が未配置`;
  const down = issue.match(/^floor (\d+) marker stairsDown$/);
  if (down) return `地下${down[1]}階に「stairsDown」が必要`;
  if (issue === "trial home") return "家マップが必要";
  if (issue === "trial dungeon floors") return "ダンジョンマップが必要";
  if (issue === "dungeon floors must be unique and contiguous") return "地下階を1階から重複なく連続させる必要があります";
  if (issue.includes("unreachable")) return "必須地点同士を通行可能にする必要があります";
  return issue;
}
function renderValidation(): void { if (!active) return; const issues = [...validateMap(active), ...missingAssetIds(active).map((id) => `missing asset ${id}`)]; validation.innerHTML = issues.length ? issues.map((issue) => `<p class="error">${escapeHtml(describeValidationIssue(issue))}</p>`).join("") : `<p class="ok">検証OK</p>`; const home = maps.find((map) => map.kind === "home"), dungeons = maps.filter((map) => map.kind === "dungeon"), packIssues = home ? validateTrialMapPack({ home, dungeons }) : ["trial home"], missingAssets = maps.flatMap(missingAssetIds); const allIssues = [...new Set([...packIssues.map(describeValidationIssue), ...missingAssets.map((id) => `素材「${id}」が見つかりません`)])], tryButton = q<HTMLButtonElement>("[data-action=try]"); tryButton.disabled = allIssues.length > 0; gameStartStatus.textContent = allIssues.length ? `開始条件: ${allIssues.join("／")}` : "開始できます"; gameStartStatus.classList.toggle("ready", allIssues.length === 0); tryButton.title = allIssues.join("\n"); }
function render(): void { renderPaletteTabs(); renderAssetOptions(); renderSource(); renderPalette(); if (!active) return; renderList(); renderEnemyRoster(); renderMapActorStrip(); renderMap(); renderValidation(); }
function setEditorMode(mode: EditorMode): void {
  // Preserve the current map's tile-size context before palette mode starts
  // accepting pages of every size.
  if (mode === "palette" && editorMode !== "palette") selectPageForMap();
  editorMode = mode;
  selectPageForEditor();
  if (mode === "map" || mode === "palette") q<HTMLElement>(`[data-palette-host="${mode}"]`).append(palettePanel);
  editorRoot.querySelectorAll<HTMLElement>("[data-editor-view]").forEach((view) => { view.hidden = view.dataset.editorView !== mode; });
  editorRoot.querySelectorAll<HTMLButtonElement>("[data-editor-mode]").forEach((button) => { button.classList.toggle("active", button.dataset.editorMode === mode); });
  manualMapActions.hidden = mode !== "map";
  if (mode === "actors") { renderActorPreviewOptions(); drawActorPreview(); }
  else if (mode === "spawns") spawnEditor.render();
  else if (mode !== "themes") { renderPaletteTabs(); renderAssetOptions(); renderPalette(); renderSource(); }
}
function canvasPoint(canvas: HTMLCanvasElement, event: PointerEvent, cellPixels: number): CellPoint { const rect = canvas.getBoundingClientRect(), pixelX = (event.clientX - rect.left) * (canvas.width / rect.width), pixelY = (event.clientY - rect.top) * (canvas.height / rect.height); return { x: Math.floor(pixelX / cellPixels), y: Math.floor(pixelY / cellPixels) }; }
function sourcePoint(event: PointerEvent): CellPoint | undefined { const asset = sourceAsset(); if (!asset) return undefined; const point = canvasPoint(sourceCanvas, event, sourceCellPixels); return inside(asset.columns, asset.rows, point) ? point : undefined; }
function palettePoint(event: PointerEvent): CellPoint | undefined { if (!pageForEditor()) return undefined; const point = canvasPoint(paletteCanvas, event, paletteCellPixels); return inside(paletteRenderedColumns, paletteRenderedRows, point) ? point : undefined; }
function mapPoint(event: PointerEvent): CellPoint | undefined { if (!active) return undefined; const point = canvasPoint(mapCanvas, event, mapCellPixels); return inside(active.width, active.height, point) ? point : undefined; }
function makeMapStampAdapter(map: MapDocument) { return { width: map.width, height: map.height, layers: map.layers, collision: map.collision }; }
function useStamp(point: CellPoint, operation: "paint" | "fill" | "rectangle", end?: CellPoint): void { if (!active) return; const stamp = selectedStamp(); if (!stamp) { status.textContent = "先にパレットで素材を選択してください。"; return; } mutateMap(() => { const adapter = makeMapStampAdapter(active!); const result = operation === "paint" ? paintPaletteStamp(adapter, stamp, point, attributeSettings()) : operation === "fill" ? fillPaletteStamp(adapter, stamp, point, attributeSettings()) : rectanglePaletteStamp(adapter, stamp, point, end!, attributeSettings()); if (!result) { status.textContent = operation === "fill" ? "塗りつぶしは単一セルのスタンプだけに使えます。" : "素材がマップ外へ出るため配置しませんでした。"; return; } syncAllComposite(active!); }); }
function markerVisual(): MapMarker["visual"] | undefined { const stamp = selectedStamp(); if (!stamp || stamp.width !== 1 || stamp.height !== 1 || !stamp.cells[0]) return undefined; return { assetId: stamp.cells[0].assetId, frame: stamp.cells[0].frame }; }
function applyMapCell(point: CellPoint): void { if (!active) return; const index = cellIndex(active, point); if (tool.value === "paint") return useStamp(point, "paint"); if (tool.value === "fill") return useStamp(point, "fill"); if (tool.value === "collision-walkable" || tool.value === "collision-blocked") { mutateMap(() => { active!.collision[index] = tool.value === "collision-walkable"; }); return; } if (tool.value === "erase") { mutateMap(() => { active!.layers[layer.value as ManualLayer][index] = null; syncComposite(active!, index); }); return; } if (tool.value === "eyedropper") { const current = active.layers[layer.value as ManualLayer][index]; if (!current) return; const page = ensurePalettePage(); if (!page) return; const matched = page.cells.find((cell) => cell.assetId === current.assetId && cell.frame === current.frame); if (matched) paletteRect = { x: matched.x, y: matched.y, width: 1, height: 1 }; else { palettes.mutate(() => { page.cells = page.cells.filter((cell) => cell.x !== 0 || cell.y !== 0); page.cells.push({ x: 0, y: 0, assetId: current.assetId, frame: current.frame, layer: layer.value as ManualLayer, walkable: active!.collision[index] }); }); paletteRect = { x: 0, y: 0, width: 1, height: 1 }; } render(); return; } if (tool.value === "marker") { const markerKind = marker.value as MapMarkerKind, needsVisual = markerKind === "stairsUp" || markerKind === "stairsDown", visual = markerVisual(); if (needsVisual && !visual) { status.textContent = "階段はパレットから単一セルを選んでから配置してください。"; return; } mutateMap(() => { active!.markers = active!.markers.filter((entry) => entry.kind !== markerKind); addMarker(active!, { id: `${markerKind}-${active!.id}`, kind: markerKind, x: point.x, y: point.y, visual }); }); } }
function download(name: string, value: unknown): void { const link = document.createElement("a"), url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
function createMap(): MapDocument | undefined { const width = Number(mapWidth.value), height = Number(mapHeight.value), size = Number(tileSize.value) as 16 | 32, requestedKind = mapKind.value as "home" | "dungeon"; try { return createManualMap(requestedKind, `${requestedKind === "home" ? "新しい家" : "新しいダンジョン"}`, { width, height, tileSize: size, floor: requestedKind === "home" ? 0 : smallestMissingDungeonFloor(maps) }); } catch (error) { status.textContent = error instanceof Error ? error.message : "マップを作成できません。"; return undefined; } }
async function loadPalettes(): Promise<void> { try { const response = await fetch("/__map-editor/palettes", { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error("palette endpoint unavailable"); const incoming = await response.json(); const errors = validatePaletteLayout(incoming, assets); if (errors.length) throw new Error(errors.join(", ")); palettes.reload(incoming as PaletteLayout); status.textContent = "パレットを再読込しました。"; } catch { palettes.reload(clonePaletteLayout(DEFAULT_PALETTE_LAYOUT as unknown as PaletteLayout)); status.textContent = "標準パレットを読み込みました。"; } selectPageForEditor(); render(); }
async function savePalettes(): Promise<void> { if (!import.meta.env.DEV) { download("palettes.json", palettes.layout); status.textContent = "本番版ではパレットJSONを書き出しました。"; return; } try { const response = await fetch("/__map-editor/palettes", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(palettes.layout) }); if (!response.ok) throw new Error(await response.text()); palettes.markSaved(); status.textContent = "パレットを保存しました。"; } catch (error) { status.textContent = `パレット保存エラー: ${error instanceof Error ? error.message : "不明"}`; } render(); }

mapCanvas.onpointerdown = (event) => { const point = mapPoint(event); if (!point) return; mapDragging = true; mapStart = point; mapLastApplied = point; mapCanvas.setPointerCapture(event.pointerId); if (tool.value !== "rectangle") applyMapCell(point); };
mapCanvas.onpointermove = (event) => { if (!mapDragging || !["paint", "collision-walkable", "collision-blocked"].includes(tool.value)) return; const point = mapPoint(event); if (!point || (mapLastApplied?.x === point.x && mapLastApplied.y === point.y)) return; mapLastApplied = point; applyMapCell(point); };
mapCanvas.onpointerup = (event) => { if (!mapDragging) return; const end = mapPoint(event); if (tool.value === "rectangle" && mapStart && end) useStamp(mapStart, "rectangle", end); mapDragging = false; mapStart = undefined; mapLastApplied = undefined; if (mapCanvas.hasPointerCapture(event.pointerId)) mapCanvas.releasePointerCapture(event.pointerId); render(); };
mapCanvas.onpointercancel = () => { mapDragging = false; mapStart = undefined; mapLastApplied = undefined; };
sourceCanvas.onpointerdown = (event) => { const point = sourcePoint(event); if (!point) return; const selected = sourceRect && point.x >= sourceRect.x && point.x < sourceRect.x + sourceRect.width && point.y >= sourceRect.y && point.y < sourceRect.y + sourceRect.height; sourceDrag = { start: point, moved: false, existing: Boolean(selected) }; if (!selected) sourceRect = { x: point.x, y: point.y, width: 1, height: 1 }; renderSource(); };
sourceCanvas.onpointermove = (event) => { if (!sourceDrag || sourceDrag.existing) return; const point = sourcePoint(event); if (!point) return; sourceDrag.moved = true; sourceRect = paletteRectFromPoints(sourceDrag.start, point); renderSource(); };
sourceCanvas.onpointercancel = () => { sourceDrag = undefined; };
paletteCanvas.onpointerdown = (event) => { const point = palettePoint(event); if (!point) return; const current = paletteRect, inSelection = current && point.x >= current.x && point.x < current.x + current.width && point.y >= current.y && point.y < current.y + current.height; paletteDrag = { start: point, moved: false, original: inSelection ? current : undefined }; if (!inSelection) { paletteRect = { x: point.x, y: point.y, width: 1, height: 1 }; renderPalette(); } };
paletteCanvas.onpointermove = (event) => { if (!paletteDrag) return; const point = palettePoint(event); if (!point) return; if (paletteDrag.original) { paletteDrag.moved ||= point.x !== paletteDrag.start.x || point.y !== paletteDrag.start.y; return; } paletteDrag.moved = true; paletteRect = paletteRectFromPoints(paletteDrag.start, point); renderPalette(); };
paletteCanvas.onpointerup = (event) => { const point = palettePoint(event), drag = paletteDrag; paletteDrag = undefined; if (!point || !drag?.original || !drag.moved) return; const page = pageForEditor(); if (!page || (point.x === drag.original.x && point.y === drag.original.y)) return; const mode = event.shiftKey ? "copy" : "move"; const success = palettes.mutate(() => { if (!transferPaletteRegion(page, drag.original!, point, mode)) status.textContent = "パレット範囲外へは移動できません。"; }); if (success) { paletteRect = { x: point.x, y: point.y, width: drag.original.width, height: drag.original.height }; render(); } };
document.addEventListener("pointerup", (event) => { if (!sourceDrag || !sourceRect || !sourceAsset()) return; const target = document.elementFromPoint(event.clientX, event.clientY); if (target !== paletteCanvas) { sourceDrag = undefined; return; } const page = ensurePalettePage(), point = palettePoint(event as PointerEvent), asset = sourceAsset(); sourceDrag = undefined; if (!page || !point || !asset) return; const changed = palettes.mutate(() => { if (!placeSourceFrames(page, point, asset, sourceRect!)) status.textContent = asset.tileSize !== page.tileSize ? `${asset.tileSize}px素材は${page.tileSize}pxパレットへ配置できません。同じセルサイズのパレットを選択してください。` : "素材範囲がパレット外へ出るため登録しませんでした。"; }); if (changed) { paletteRect = { x: point.x, y: point.y, width: sourceRect.width, height: sourceRect.height }; render(); } });
document.addEventListener("keydown", (event) => { if (event.key !== "Delete" || !paletteRect) return; const page = pageForEditor(); if (!page) return; event.preventDefault(); palettes.mutate(() => { page.cells = page.cells.filter((cell) => cell.x < paletteRect!.x || cell.x >= paletteRect!.x + paletteRect!.width || cell.y < paletteRect!.y || cell.y >= paletteRect!.y + paletteRect!.height); }); render(); });

kind.onchange = () => { const candidate = maps.filter((map) => map.kind === kind.value).sort((a, b) => a.floor - b.floor)[0]; if (candidate) setActive(candidate); else render(); };
mapKind.onchange = syncFloorControls;
root.querySelectorAll<HTMLButtonElement>("[data-editor-mode]").forEach((button) => button.onclick = () => setEditorMode(button.dataset.editorMode as EditorMode));
layer.onchange = () => { const visibility = layerVisibility.get(layer.value as ManualLayer); if (visibility) visibility.checked = true; render(); };
for (const visibility of layerVisibility.values()) visibility.onchange = renderMap;
zoom.onchange = render; grid.onchange = render; pass.onchange = render;
assetSelect.onchange = () => { selectedAssetId = assetSelect.value; sessionStorage.setItem(selectedAssetStorageKey, selectedAssetId); sourceRect = undefined; renderSource(); };
root.querySelectorAll<HTMLButtonElement>("[data-asset-size-filter]").forEach((button) => button.onclick = () => {
  assetSizeFilter = button.dataset.assetSizeFilter as AssetSizeFilter;
  root.querySelectorAll<HTMLButtonElement>("[data-asset-size-filter]").forEach((entry) => entry.classList.toggle("active", entry === button));
  sourceRect = undefined;
  revealSelectedAsset = true;
  renderAssetOptions(); renderSource();
});
assetSearch.oninput = () => { assetSearchQuery = assetSearch.value; sourceRect = undefined; renderAssetOptions(); renderSource(); };
q<HTMLButtonElement>("[data-action=asset-refresh]").onclick = async () => { await loadAssetCatalog(); await loadPalettes(); status.textContent = `素材一覧を更新しました（${assets.length}枚）。`; render(); };
actorPreviewId.onchange = () => { actorPreviewState = { action: "idle", direction: "down", frame: 0, elapsedMs: 0 }; renderActorPreviewOptions(); drawActorPreview(); };
actorPreviewAction.onchange = () => { actorPreviewState = { ...actorPreviewState, action: actorPreviewAction.value, frame: 0, elapsedMs: 0 }; renderActorPreviewOptions(); drawActorPreview(); };
actorPreviewDirection.onchange = () => { actorPreviewState = { ...actorPreviewState, direction: actorPreviewDirection.value as ActorPreviewState["direction"], frame: 0, elapsedMs: 0 }; drawActorPreview(); };
q<HTMLButtonElement>("[data-action=actor-settings-save]").onclick = () => { void saveActorSettings(); };
applyFloorButton.onclick = async () => {
  if (!active || active.kind !== "dungeon") return;
  try {
    const requestedFloor = Number(mapFloor.value);
    const updates = planDungeonFloorMove(maps, active.id, requestedFloor);
    if (!updates.length) { status.textContent = `地下${active.floor}階のままです。`; return; }
    applyDungeonFloorUpdates(maps, updates);
    applyDungeonFloorUpdates([active], updates);
    for (const update of updates) {
      const map = maps.find((candidate) => candidate.id === update.id);
      if (!map) continue;
      touch(map);
      await repository.save(map);
    }
    touch(active);
    mapFloor.value = String(active.floor);
    status.textContent = `地下${active.floor}階へ移動しました。間の階層は自動的に並べ替えました。`;
    render();
  } catch (error) {
    status.textContent = error instanceof Error ? error.message : "階層を変更できません。";
    mapFloor.value = String(active.floor);
  }
};
q<HTMLButtonElement>("[data-action=apply-map-settings]").onclick = () => { if (!active) return; const width = Number(mapWidth.value), height = Number(mapHeight.value), requestedSize = Number(tileSize.value) as 16 | 32, requestedKind = mapKind.value as "home" | "dungeon"; mutateMap(() => { const result = applyMapSettingsAtomically(active!, { width, height, tileSize: requestedSize, kind: requestedKind, maps }); if (!result.ok) status.textContent = result.reason; }); kind.value = active.kind; mapKind.value = active.kind; mapFloor.value = String(active.floor); mapWidth.value = String(active.width); mapHeight.value = String(active.height); tileSize.value = String(active.tileSize); syncFloorControls(); selectPageForMap(); updateMarkerOptions(); render(); };
q<HTMLButtonElement>("[data-action=undo]").onclick = async () => { if (!active) return; const history = historyFor(active), previous = history.undo.pop(); if (!previous) return; history.redo.push(mapSnapshot()); active = previous; await saveActive(); selectPageForMap(); render(); };
q<HTMLButtonElement>("[data-action=redo]").onclick = async () => { if (!active) return; const history = historyFor(active), next = history.redo.pop(); if (!next) return; history.undo.push(mapSnapshot()); active = next; await saveActive(); selectPageForMap(); render(); };
q<HTMLButtonElement>("[data-action=new]").onclick = async () => { const next = createMap(); if (!next) return; maps.push(next); await repository.save(next); setActive(next); status.textContent = next.kind === "dungeon" ? `最小の欠番である地下${next.floor}階を作成しました。` : "家マップを作成しました。"; };
q<HTMLButtonElement>("[data-action=rename]").onclick = () => { if (!active) return; const name = prompt("マップ名", active.name); if (name?.trim()) mutateMap(() => { active!.name = name.trim(); }); };
q<HTMLButtonElement>("[data-action=duplicate]").onclick = async () => { if (!active) return; const copy = cloneMap(active); try { copy.floor = copy.kind === "home" ? 0 : smallestMissingDungeonFloor(maps); } catch (error) { status.textContent = error instanceof Error ? error.message : "階番号を割り当てられません。"; return; } copy.id = uniqueId("map"); copy.name += " コピー"; copy.createdAt = new Date().toISOString(); copy.updatedAt = copy.createdAt; copy.markers = copy.markers.map((entry) => ({ ...entry, id: `${entry.kind}-${copy.id}` })); maps.push(copy); await repository.save(copy); status.textContent = copy.kind === "dungeon" ? `欠番の第${copy.floor}階として複製しました。` : "家マップを複製しました。"; setActive(copy); };
q<HTMLButtonElement>("[data-action=delete]").onclick = async () => { if (!active) return; const deleting = active, hasLaterFloors = deleting.kind === "dungeon" && maps.some((map) => map.kind === "dungeon" && map.floor > deleting.floor), message = hasLaterFloors ? `「${deleting.name}」（第${deleting.floor}階）を削除しますか？\n後続階は自動的に詰められ、階段の接続先も新しい階番号に変わります。` : `「${deleting.name}」を削除しますか？`; if (!confirm(message)) return; const remaining = maps.filter((map) => map.id !== deleting.id); let floorUpdates: ReturnType<typeof planDungeonFloorCompaction>; try { floorUpdates = planDungeonFloorCompaction(remaining); } catch (error) { status.textContent = error instanceof Error ? error.message : "階番号を整理できません。"; return; } applyDungeonFloorUpdates(remaining, floorUpdates); await repository.delete(deleting.id); maps = remaining; for (const update of floorUpdates) { const map = maps.find((value) => value.id === update.id); if (map) await repository.save(map); } const next = maps.find((map) => map.kind === kind.value) ?? maps[0]; if (next) { setActive(next); status.textContent = floorUpdates.length ? `${deleting.name}を削除し、後続階を詰めました。階段接続は新しい連続階に従います。` : `${deleting.name}を削除しました。`; } else { const created = createMap(); if (created) { maps = [created]; await repository.save(created); setActive(created); } } };
q<HTMLButtonElement>("[data-action=export-map]").onclick = () => { if (active) download(`${active.id}.json`, active); };
q<HTMLButtonElement>("[data-action=export-pack]").onclick = () => download("map-pack.json", { version: 6, maps });
q<HTMLButtonElement>("[data-action=try]").onclick = () => { const home = maps.find((map) => map.kind === "home"), dungeons = maps.filter((map) => map.kind === "dungeon").sort((a, b) => a.floor - b.floor); if (!home) return; const pack = { home, dungeons }, issues = validateTrialMapPack(pack); if (issues.length) { status.textContent = `ゲームを開始できません: ${issues.join(", ")}`; render(); return; } storeTrialMapPack(pack); window.location.href = "./?autostart=world"; };
const addPalette = () => { const context = editorMode === "palette" ? activePage() : undefined, id = uniqueId("palette"), pageKind = context?.mapKind ?? active?.kind ?? "dungeon", pageTileSize = editorMode === "palette" ? sourceAsset()?.tileSize ?? context?.tileSize ?? 16 : active?.tileSize ?? 16; palettes.mutate((layout) => addPalettePage(layout, createPalettePage({ id, label: `新しいパレット ${pageTileSize}px`, mapKind: pageKind, tileSize: pageTileSize, width: 2048, height: 2048 }))); activePageId = id; paletteRect = undefined; render(); };
q<HTMLButtonElement>("[data-action=palette-add]").onclick = addPalette;
q<HTMLButtonElement>("[data-action=palette-add-current]").onclick = addPalette;
q<HTMLButtonElement>("[data-action=palette-rename]").onclick = () => { const page = activePage(); if (!page) return; const label = prompt("パレット名", page.label); if (label) palettes.mutate(() => { if (!renamePalettePage(page, label)) status.textContent = "名前を入力してください。"; }); render(); };
q<HTMLButtonElement>("[data-action=palette-resize]").onclick = () => { const page = activePage(); if (!page) return; const width = Number(prompt(`幅（1〜${MAX_PALETTE_DIMENSION}セル）`, String(page.width))), height = Number(prompt(`高さ（1〜${MAX_PALETTE_DIMENSION}セル）`, String(page.height))); palettes.mutate(() => { const result = resizePalettePage(page, width, height); if (!result.ok) status.textContent = result.reason; }); render(); };
q<HTMLButtonElement>("[data-action=palette-delete]").onclick = () => { const page = activePage(); if (!page) return; if (palettes.layout.pages.length <= 1) { status.textContent = "最後のパレットページは削除できません。保存可能なページを1つ残してください。"; render(); return; } if (!confirm(`パレット「${page.label}」を削除しますか？`)) return; palettes.mutate((layout) => { deletePalettePage(layout, page.id); }); selectPageForEditor(); render(); };
q<HTMLButtonElement>("[data-action=palette-undo]").onclick = () => { palettes.undo(); selectPageForEditor(); render(); };
q<HTMLButtonElement>("[data-action=palette-redo]").onclick = () => { palettes.redo(); selectPageForEditor(); render(); };
q<HTMLButtonElement>("[data-action=palette-tag]").onclick = () => {
  const page = pageForEditor();
  if (!page || !paletteRect) { status.textContent = "パレット上で範囲を選んでから適用してください。"; return; }
  // "-" clears the field; an empty select leaves it as it is.
  const role = tagRole.value === "" ? undefined : tagRole.value === "-" ? null : tagRole.value as PaletteCellRole;
  const statusValue = tagStatus.value === "" ? undefined : tagStatus.value as PaletteCellStatus;
  const note = tagNote.value.trim() ? tagNote.value : null;
  if (role === undefined && statusValue === undefined && note === null) { status.textContent = "用途か状態を選んでから適用してください。"; return; }
  let changed = 0;
  const pageId = page.id, rect = paletteRect;
  palettes.mutate((layout) => {
    const target = layout.pages.find((entry) => entry.id === pageId);
    if (target) changed = tagPaletteRegion(target, rect, { role, status: statusValue, note });
  });
  status.textContent = changed ? `${changed}枚に仕分けを適用しました。保存すると反映されます。` : "選択範囲に変更はありませんでした。";
  render();
};
q<HTMLButtonElement>("[data-action=palette-save]").onclick = () => { void savePalettes(); };
q<HTMLButtonElement>("[data-action=palette-reload]").onclick = () => { void loadPalettes(); };
q<HTMLButtonElement>("[data-action=palette-export]").onclick = () => download("palettes.json", palettes.layout);
importInput.onchange = async () => { const file = importInput.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()) as { maps?: unknown[] }; const incoming = (Array.isArray(parsed.maps) ? parsed.maps : [parsed]).map(normalizeMap); for (const value of incoming) { maps = maps.some((map) => map.id === value.id) ? maps.map((map) => map.id === value.id ? value : map) : [...maps, value]; await repository.save(value); } if (incoming[0]) setActive(incoming[0]); status.textContent = `${incoming.length}件を読み込みました。`; } catch (error) { status.textContent = `読み込みエラー: ${error instanceof Error ? error.message : "不正なJSON"}`; } };
assetImportInput.onchange = async () => {
  const selected = [...(assetImportInput.files ?? [])];
  if (!selected.length) return;
  try {
    let body: Blob, fileName: string;
    if (selected.length === 1) { body = selected[0]!; fileName = selected[0]!.name; }
    else { const entries: Record<string, Uint8Array> = {}; for (const file of selected) entries[file.name] = new Uint8Array(await file.arrayBuffer()); body = new Blob([zipSync(entries)], { type: "application/zip" }); fileName = "selection.zip"; }
    const response = await fetch("/__map-editor/import/analyze", { method: "POST", headers: { "Content-Type": "application/octet-stream", "X-Import-Filename": encodeURIComponent(fileName) }, body });
    const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "解析に失敗しました");
    pendingImport = { id: payload.id, analysis: payload.analysis }; renderImportReport(); status.textContent = "素材を解析しました。内容を確認して承認してください。";
  } catch (error) { status.textContent = `素材解析エラー: ${error instanceof Error ? error.message : "不明"}`; }
  assetImportInput.value = "";
};
void (async () => {
  await loadActorSettings();
  await loadAssetCatalog();
  await loadPalettes();
  setEditorMode(editorMode);
  try {
    maps = await repository.list();
    if (!maps.length) { const defaults = createDefaultMapPack(); maps = [defaults.home, ...defaults.dungeons]; for (const map of maps) await repository.save(map); }
    const initialMap = maps.find((map) => map.kind === "home") ?? maps[0];
    if (initialMap) setActive(initialMap);
  } catch (error) {
    status.textContent = `素材とパレットは利用できます。手動マップの読み込みだけ失敗しました: ${error instanceof Error ? error.message : "不明"}`;
    render();
  }
  window.requestAnimationFrame(animateActorPreview);
})();
