import "./review.css";
import { DEFAULT_PALETTE_LAYOUT, MAP_ASSET_CATALOG } from "../game/mapAssetCatalog.generated";
import { addMarker, cloneMap, createManualMap, MapRepository, normalizeMap, storeTrialMapPack, validateMap, validateTrialMapPack, type ManualLayer, type MapDocument, type MapMarker, type MapMarkerKind } from "../game/mapDocument";
import { PaletteHistory, addPalettePage, clonePaletteLayout, createPalettePage, deletePalettePage, fillPaletteStamp, paintPaletteStamp, paletteRectFromPoints, paletteStamp, placeSourceFrames, rectanglePaletteStamp, renamePalettePage, resizePalettePage, transferPaletteRegion, validatePaletteLayout, type CellPoint, type CellRect, type CollisionMode, type PaletteAsset, type PaletteLayout, type PalettePage, type StampAttributeMode } from "./paletteModel";
import { fitEditorCanvas } from "./canvasSizing";
import { applyMapSettingsAtomically } from "./mapSettings";
import { applyDungeonFloorUpdates, planDungeonFloorCompaction, smallestMissingDungeonFloor } from "./floorSequence";

const root = document.querySelector<HTMLElement>("#review-app");
if (!root) throw new Error("review app root not found");

const assets: PaletteAsset[] = MAP_ASSET_CATALOG.map((asset) => ({ ...asset, mapKinds: [...asset.mapKinds] }));
const assetById = new Map(assets.map((asset) => [asset.id, asset]));
const repository = new MapRepository();
const layers: ManualLayer[] = ["ground", "structure", "decoration"];
const homeMarkers: MapMarkerKind[] = ["homeSpawn", "dungeonEntrance", "homeStorage", "homePreparation", "homeVisitors"];
const dungeonMarkers: MapMarkerKind[] = ["stairsUp", "stairsDown"];
const sourceScale = 2;

root.innerHTML = `
  <div class="map-editor-shell">
    <header class="map-editor-header"><div><p class="map-editor-eyebrow">AUTHORED TILE PALETTE</p><h1>家・ダンジョン マップエディター</h1><p>スプライトシートから自由なパレットを作り、矩形スタンプとして配置します。</p></div>
      <div class="map-editor-header-actions"><button data-action="new">新規マップ</button><button data-action="rename">名前変更</button><button data-action="duplicate">複製</button><button data-action="delete">削除</button><button data-action="undo">元に戻す</button><button data-action="redo">やり直す</button><button class="primary" data-action="try">全マップを試遊</button></div></header>
    <section class="map-editor-toolbar">
      <label>一覧表示 <select data-kind><option value="home">家</option><option value="dungeon">ダンジョン</option></select></label>
      <label>マップ種類 <select data-map-kind><option value="home">家</option><option value="dungeon">ダンジョン</option></select></label><label>幅 <input data-map-width type="number" min="4" max="256"></label><label>高さ <input data-map-height type="number" min="4" max="256"></label>
      <label>セル <select data-tile-size><option value="16">16px</option><option value="32">32px</option></select></label><button data-action="apply-map-settings">サイズを適用</button>
      <label>レイヤー <select data-layer><option value="ground">ground</option><option value="structure">structure</option><option value="decoration">decoration</option></select></label>
      <label>道具 <select data-tool><option value="paint">鉛筆（スタンプ）</option><option value="rectangle">矩形（繰り返し）</option><option value="fill">塗りつぶし（単体のみ）</option><option value="erase">消去</option><option value="eyedropper">スポイト</option><option value="marker">マーカー</option><option value="collision-walkable">通行可</option><option value="collision-blocked">通行不可</option></select></label>
      <label>属性 <select data-attribute-mode><option value="palette">パレット設定</option><option value="manual">手動設定</option></select></label><label>手動通行 <select data-collision-mode><option value="unchanged">変更しない</option><option value="walkable">通行可</option><option value="blocked">通行不可</option></select></label>
      <label class="check"><input type="checkbox" data-grid checked>グリッド</label><label class="check"><input type="checkbox" data-pass checked>通行表示</label><label>ズーム <select data-zoom><option value="1">100%</option><option value="1.5">150%</option><option value="2">200%</option></select></label>
    </section>
    <main class="map-editor-layout">
      <aside class="map-editor-side"><div class="panel-heading"><h2>マップ</h2><span data-map-count></span></div><div class="map-list" data-map-list></div><div class="map-actions"><button data-action="export-map">現在JSON</button><button data-action="export-pack">試遊パックJSON</button><label class="file-button">JSON読込<input type="file" accept="application/json" data-import></label></div><hr>
        <h2>マーカー</h2><label>種類 <select data-marker></select></label><p class="small">マーカー道具でセルをクリックします。stairsUp / stairsDownには、パレットの単一セルを見た目として設定します。</p><p class="save-status" data-status>読み込み中…</p></aside>
      <section class="map-canvas-panel"><div class="panel-heading"><h2 data-map-title>マップ</h2><span data-stamp-info>スタンプ未選択</span></div><p class="canvas-fit-warning" data-canvas-fit hidden></p><div class="map-canvas-wrap"><canvas data-map-canvas></canvas></div><div class="map-canvas-help">鉛筆は選択矩形の左上を配置します。矩形は選択パターンを繰り返し、空白セルは既存マップを消しません。素材がマップ外へ出る操作は全体を拒否します。</div><div class="map-validation" data-validation></div></section>
      <aside class="map-editor-side palette-panel"><div class="panel-heading"><h2>自由配置パレット</h2><span data-palette-dirty></span></div><div class="palette-tabs" data-palette-tabs></div><div class="palette-actions"><button data-action="palette-add">ページ追加</button><button data-action="palette-rename">改名</button><button data-action="palette-resize">拡縮</button><button data-action="palette-delete">削除</button><button data-action="palette-undo">戻す</button><button data-action="palette-redo">やり直す</button><button data-action="palette-save">保存</button><button data-action="palette-reload">再読込</button><button data-action="palette-export">JSON書出し</button></div><div class="palette-wrap"><canvas data-palette-canvas></canvas></div>
        <p class="small">パレット上をドラッグして矩形を選択します。選択後にドラッグすると移動、Shift+ドラッグで複製、Deleteで削除できます。シート選択をパレットへドラッグすると登録できます。</p><hr><h2>素材シート</h2><label>素材 <select data-asset></select></label><div class="source-wrap"><canvas data-source-canvas></canvas></div><p class="small">シート上をドラッグして単体または矩形を選択し、パレットへドラッグしてください。</p></aside>
    </main>
  </div>`;

const q = <T extends Element>(selector: string): T => { const result = root.querySelector<T>(selector); if (!result) throw new Error(`missing editor element: ${selector}`); return result; };
const mapCanvas = q<HTMLCanvasElement>("[data-map-canvas]"), mapContext = mapCanvas.getContext("2d")!;
const paletteCanvas = q<HTMLCanvasElement>("[data-palette-canvas]"), paletteContext = paletteCanvas.getContext("2d")!;
const sourceCanvas = q<HTMLCanvasElement>("[data-source-canvas]"), sourceContext = sourceCanvas.getContext("2d")!;
const mapList = q<HTMLElement>("[data-map-list]"), paletteTabs = q<HTMLElement>("[data-palette-tabs]"), validation = q<HTMLElement>("[data-validation]"), status = q<HTMLElement>("[data-status]");
const mapCount = q<HTMLElement>("[data-map-count]"), mapTitle = q<HTMLElement>("[data-map-title]"), stampInfo = q<HTMLElement>("[data-stamp-info]"), paletteDirty = q<HTMLElement>("[data-palette-dirty]"), canvasFitWarning = q<HTMLElement>("[data-canvas-fit]");
const kind = q<HTMLSelectElement>("[data-kind]"), mapKind = q<HTMLSelectElement>("[data-map-kind]"), mapWidth = q<HTMLInputElement>("[data-map-width]"), mapHeight = q<HTMLInputElement>("[data-map-height]"), tileSize = q<HTMLSelectElement>("[data-tile-size]"), layer = q<HTMLSelectElement>("[data-layer]"), tool = q<HTMLSelectElement>("[data-tool]"), attributeMode = q<HTMLSelectElement>("[data-attribute-mode]"), collisionMode = q<HTMLSelectElement>("[data-collision-mode]"), marker = q<HTMLSelectElement>("[data-marker]"), zoom = q<HTMLSelectElement>("[data-zoom]"), assetSelect = q<HTMLSelectElement>("[data-asset]"), importInput = q<HTMLInputElement>("[data-import]");
const grid = q<HTMLInputElement>("[data-grid]"), pass = q<HTMLInputElement>("[data-pass]");

let maps: MapDocument[] = [], active: MapDocument | undefined;
let palettes = new PaletteHistory(clonePaletteLayout(DEFAULT_PALETTE_LAYOUT as unknown as PaletteLayout));
let activePageId = "", selectedAssetId = "";
let sourceRect: CellRect | undefined, paletteRect: CellRect | undefined, mapStart: CellPoint | undefined;
let mapDragging = false;
let sourceDrag: { start: CellPoint; moved: boolean; existing: boolean } | undefined;
let paletteDrag: { start: CellPoint; moved: boolean; original?: CellRect } | undefined;
let mapCellPixels = 16, paletteCellPixels = 16, sourceCellPixels = 16;
const mapHistory = new Map<string, { undo: MapDocument[]; redo: MapDocument[] }>(), images = new Map<string, HTMLImageElement>();
for (const asset of assets) { const image = new Image(); image.onload = () => render(); image.src = asset.path; images.set(asset.id, image); }

const uniqueId = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
const activePage = (): PalettePage | undefined => palettes.layout.pages.find((page) => page.id === activePageId);
const catalogAsset = (id: string) => assetById.get(id);
const pageForActiveMap = (): PalettePage | undefined => { const current = active; return current ? palettes.layout.pages.find((page) => page.id === activePageId && page.mapKind === current.kind && page.tileSize === current.tileSize) : undefined; };
const mapSize = (map: MapDocument) => map.width * map.height;
const cellIndex = (map: MapDocument, point: CellPoint) => point.y * map.width + point.x;
const inside = (width: number, height: number, point: CellPoint) => point.x >= 0 && point.y >= 0 && point.x < width && point.y < height;
function frameSource(asset: PaletteAsset, frame: number): { x: number; y: number } { const column = frame % asset.columns, row = Math.floor(frame / asset.columns); return { x: asset.margin + column * (asset.tileSize + asset.spacing), y: asset.margin + row * (asset.tileSize + asset.spacing) }; }
function drawAsset(context: CanvasRenderingContext2D, assetId: string, frameNumber: number, dx: number, dy: number, size: number): void { const asset = catalogAsset(assetId), image = images.get(assetId); if (!asset || !image?.complete || image.naturalWidth === 0 || frameNumber < 0 || frameNumber >= asset.frameCount) { context.fillStyle = "#a94055"; context.fillRect(dx, dy, size, size); context.strokeStyle = "#ffd5db"; context.beginPath(); context.moveTo(dx, dy); context.lineTo(dx + size, dy + size); context.moveTo(dx + size, dy); context.lineTo(dx, dy + size); context.stroke(); return; } const source = frameSource(asset, frameNumber); context.drawImage(image, source.x, source.y, asset.tileSize, asset.tileSize, dx, dy, size, size); }
function selectedStamp() { const page = pageForActiveMap(); return page && paletteRect ? paletteStamp(page, paletteRect) : undefined; }
function sourceAsset(): PaletteAsset | undefined { return catalogAsset(selectedAssetId); }
function attributeSettings() { return { mode: attributeMode.value as StampAttributeMode, layer: layer.value as ManualLayer, collision: collisionMode.value as CollisionMode }; }
function historyFor(map: MapDocument) { let value = mapHistory.get(map.id); if (!value) { value = { undo: [], redo: [] }; mapHistory.set(map.id, value); } return value; }
function mapSnapshot(): MapDocument { if (!active) throw new Error("no active map"); return cloneMap(active); }
function syncComposite(map: MapDocument, index: number): void { const value = map.layers.decoration[index] ?? map.layers.structure[index] ?? map.layers.ground[index]; map.terrain[index] = value?.assetId ?? null; }
function syncAllComposite(map: MapDocument): void { for (let index = 0; index < mapSize(map); index += 1) syncComposite(map, index); }
function touch(map: MapDocument): void { map.updatedAt = new Date().toISOString(); }
async function saveActive(): Promise<void> { if (!active) return; maps = maps.map((map) => map.id === active!.id ? cloneMap(active!) : map); await repository.save(active); renderList(); }
function mutateMap(action: () => void): void { if (!active) return; const before = mapSnapshot(); action(); if (JSON.stringify(before) !== JSON.stringify(active)) { historyFor(active).undo.push(before); historyFor(active).redo = []; touch(active); void saveActive(); } render(); }
function selectPageForMap(): void { if (!active) return; const compatible = palettes.layout.pages.filter((page) => page.mapKind === active!.kind && page.tileSize === active!.tileSize); if (!compatible.some((page) => page.id === activePageId)) activePageId = compatible[0]?.id ?? ""; paletteRect = undefined; }
function ensurePalettePage(): PalettePage | undefined { if (!active) return undefined; let page = pageForActiveMap(); if (page) return page; const id = uniqueId(`${active.kind}-${active.tileSize}`); palettes.mutate((layout) => addPalettePage(layout, createPalettePage({ id, label: `${active!.kind === "home" ? "家" : "ダンジョン"} ${active!.tileSize}px`, mapKind: active!.kind, tileSize: active!.tileSize, width: 8, height: 8 }))); activePageId = id; page = activePage(); return page; }
function setActive(map: MapDocument): void { active = cloneMap(map); kind.value = active.kind; mapKind.value = active.kind; mapWidth.value = String(active.width); mapHeight.value = String(active.height); tileSize.value = String(active.tileSize); selectPageForMap(); updateMarkerOptions(); render(); }
function missingAssetIds(map: MapDocument): string[] { const values = new Set<string>(); for (const currentLayer of layers) for (const cell of map.layers[currentLayer]) if (cell && !assetById.has(cell.assetId)) values.add(cell.assetId); for (const entry of map.markers) if (entry.visual && !assetById.has(entry.visual.assetId)) values.add(entry.visual.assetId); return [...values]; }
function updateMarkerOptions(): void { if (!active) return; const kinds = active.kind === "home" ? homeMarkers : dungeonMarkers; marker.innerHTML = kinds.map((value) => `<option value="${value}">${value}</option>`).join(""); }
function escapeHtml(value: string): string { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }
function renderList(): void { if (!active) return; const filtered = maps.filter((map) => map.kind === kind.value).sort((a, b) => a.floor - b.floor); mapCount.textContent = `${filtered.length} 枚`; mapList.innerHTML = filtered.map((map) => `<button class="map-list-item${map.id === active?.id ? " active" : ""}" data-map-id="${map.id}"><span>${escapeHtml(map.name)}</span><small>${map.kind === "home" ? "家" : `${map.floor}F`} / ${map.width}×${map.height} / ${map.tileSize}px</small></button>`).join("") || `<p class="small">この種類のマップはありません。</p>`; mapList.querySelectorAll<HTMLButtonElement>("[data-map-id]").forEach((button) => button.onclick = () => { const map = maps.find((value) => value.id === button.dataset.mapId); if (map) setActive(map); }); }
function renderPaletteTabs(): void { if (!active) return; const compatible = palettes.layout.pages.filter((page) => page.mapKind === active!.kind && page.tileSize === active!.tileSize); paletteTabs.innerHTML = compatible.map((page) => `<button data-page-id="${page.id}" class="${page.id === activePageId ? "active" : ""}">${escapeHtml(page.label)}</button>`).join("") || `<p class="small">${active.kind} / ${active.tileSize}px のページがありません。</p>`; paletteTabs.querySelectorAll<HTMLButtonElement>("[data-page-id]").forEach((button) => button.onclick = () => { activePageId = button.dataset.pageId!; paletteRect = undefined; render(); }); paletteDirty.textContent = palettes.dirty ? "未保存" : "保存済み"; }
function renderAssetOptions(): void { if (!active) return; const allowed = assets.filter((asset) => asset.mapKinds.includes(active!.kind) && asset.tileSize === active!.tileSize); if (!allowed.some((asset) => asset.id === selectedAssetId)) selectedAssetId = allowed[0]?.id ?? ""; assetSelect.innerHTML = allowed.map((asset) => `<option value="${asset.id}">${escapeHtml(asset.label)} (${asset.columns}×${asset.rows})</option>`).join(""); assetSelect.value = selectedAssetId; }
function drawSelection(context: CanvasRenderingContext2D, rect: CellRect, size: number, colour: string): void { context.lineWidth = 2; context.strokeStyle = colour; context.strokeRect(rect.x * size + 1, rect.y * size + 1, rect.width * size - 2, rect.height * size - 2); }
function renderSource(): void { const asset = sourceAsset(); if (!asset) { sourceCanvas.width = sourceCanvas.height = 1; return; } const fit = fitEditorCanvas(asset.columns, asset.rows, asset.tileSize * sourceScale); sourceCellPixels = fit.cellPixels; sourceCanvas.width = fit.width; sourceCanvas.height = fit.height; sourceContext.imageSmoothingEnabled = false; sourceContext.clearRect(0, 0, sourceCanvas.width, sourceCanvas.height); for (let frame = 0; frame < asset.frameCount; frame += 1) drawAsset(sourceContext, asset.id, frame, (frame % asset.columns) * sourceCellPixels, Math.floor(frame / asset.columns) * sourceCellPixels, sourceCellPixels); sourceContext.strokeStyle = "#ffffff33"; for (let x = 0; x <= asset.columns; x += 1) { sourceContext.beginPath(); sourceContext.moveTo(x * sourceCellPixels, 0); sourceContext.lineTo(x * sourceCellPixels, sourceCanvas.height); sourceContext.stroke(); } for (let y = 0; y <= asset.rows; y += 1) { sourceContext.beginPath(); sourceContext.moveTo(0, y * sourceCellPixels); sourceContext.lineTo(sourceCanvas.width, y * sourceCellPixels); sourceContext.stroke(); } if (sourceRect) drawSelection(sourceContext, sourceRect, sourceCellPixels, "#ffd166"); }
function renderPalette(): void { const page = pageForActiveMap(); if (!page) { paletteCanvas.width = paletteCanvas.height = 1; return; } const fit = fitEditorCanvas(page.width, page.height, page.tileSize * sourceScale); paletteCellPixels = fit.cellPixels; paletteCanvas.width = fit.width; paletteCanvas.height = fit.height; paletteContext.imageSmoothingEnabled = false; paletteContext.fillStyle = "#101725"; paletteContext.fillRect(0, 0, paletteCanvas.width, paletteCanvas.height); for (const cell of page.cells) drawAsset(paletteContext, cell.assetId, cell.frame, cell.x * paletteCellPixels, cell.y * paletteCellPixels, paletteCellPixels); paletteContext.strokeStyle = "#ffffff20"; for (let x = 0; x <= page.width; x += 1) { paletteContext.beginPath(); paletteContext.moveTo(x * paletteCellPixels, 0); paletteContext.lineTo(x * paletteCellPixels, paletteCanvas.height); paletteContext.stroke(); } for (let y = 0; y <= page.height; y += 1) { paletteContext.beginPath(); paletteContext.moveTo(0, y * paletteCellPixels); paletteContext.lineTo(paletteCanvas.width, y * paletteCellPixels); paletteContext.stroke(); } if (paletteRect) drawSelection(paletteContext, paletteRect, paletteCellPixels, "#70d9ce"); }
function drawMapCell(map: MapDocument, index: number, x: number, y: number, display: number): void { const px = x * display, py = y * display; mapContext.fillStyle = "#172130"; mapContext.fillRect(px, py, display, display); for (const currentLayer of layers) { const cell = map.layers[currentLayer][index]; if (cell) drawAsset(mapContext, cell.assetId, cell.frame, px, py, display); } if (pass.checked) { mapContext.fillStyle = map.collision[index] ? "#42d37a44" : "#ed536044"; mapContext.fillRect(px, py, display, display); } if (grid.checked) { mapContext.strokeStyle = "#ffffff24"; mapContext.strokeRect(px, py, display, display); } }
function drawMarker(entry: MapMarker, display: number): void { const px = entry.x * display, py = entry.y * display; if (entry.visual) drawAsset(mapContext, entry.visual.assetId, entry.visual.frame, px, py, display); mapContext.fillStyle = entry.visual ? "#ffd166bb" : "#ffd166"; mapContext.fillRect(px + display * .25, py + display * .25, display * .5, display * .5); mapContext.fillStyle = "#fff8d7"; mapContext.font = `${Math.max(8, display * .55)}px sans-serif`; mapContext.fillText(entry.kind, px + 2, py + Math.max(10, display * .75)); }
function renderMap(): void { if (!active) return; const requested = active.tileSize * Number(zoom.value), fit = fitEditorCanvas(active.width, active.height, requested); mapCellPixels = fit.cellPixels; mapCanvas.width = fit.width; mapCanvas.height = fit.height; mapContext.imageSmoothingEnabled = false; mapContext.clearRect(0, 0, mapCanvas.width, mapCanvas.height); for (let y = 0; y < active.height; y += 1) for (let x = 0; x < active.width; x += 1) drawMapCell(active, y * active.width + x, x, y, mapCellPixels); for (const entry of active.markers) drawMarker(entry, mapCellPixels); mapTitle.textContent = `${active.name} — ${active.width}×${active.height} / ${active.tileSize}px`; const stamp = selectedStamp(); stampInfo.textContent = stamp ? `${stamp.width}×${stamp.height} スタンプ` : "スタンプ未選択"; canvasFitWarning.hidden = !fit.reduced; canvasFitWarning.textContent = fit.reduced ? `大きなマップのため表示を ${mapCellPixels}px/セルへ自動縮小しています（指定: ${requested}px/セル）。編集座標は保持されます。` : ""; }
function renderValidation(): void { if (!active) return; const issues = [...validateMap(active), ...missingAssetIds(active).map((id) => `missing asset ${id}`)]; validation.innerHTML = issues.length ? issues.map((issue) => `<p class="error">${escapeHtml(issue)}</p>`).join("") : `<p class="ok">検証OK</p>`; const home = maps.find((map) => map.kind === "home"), dungeons = maps.filter((map) => map.kind === "dungeon"), packIssues = home ? validateTrialMapPack({ home, dungeons }) : ["trial home"]; const missingInPack = maps.some((map) => missingAssetIds(map).length > 0); q<HTMLButtonElement>("[data-action=try]").disabled = packIssues.length > 0 || missingInPack; }
function render(): void { if (!active) return; renderList(); renderPaletteTabs(); renderAssetOptions(); renderSource(); renderPalette(); renderMap(); renderValidation(); }
function canvasPoint(canvas: HTMLCanvasElement, event: PointerEvent, cellPixels: number): CellPoint { const rect = canvas.getBoundingClientRect(), pixelX = (event.clientX - rect.left) * (canvas.width / rect.width), pixelY = (event.clientY - rect.top) * (canvas.height / rect.height); return { x: Math.floor(pixelX / cellPixels), y: Math.floor(pixelY / cellPixels) }; }
function sourcePoint(event: PointerEvent): CellPoint | undefined { const asset = sourceAsset(); if (!asset) return undefined; const point = canvasPoint(sourceCanvas, event, sourceCellPixels); return inside(asset.columns, asset.rows, point) ? point : undefined; }
function palettePoint(event: PointerEvent): CellPoint | undefined { const page = pageForActiveMap(); if (!page) return undefined; const point = canvasPoint(paletteCanvas, event, paletteCellPixels); return inside(page.width, page.height, point) ? point : undefined; }
function mapPoint(event: PointerEvent): CellPoint | undefined { if (!active) return undefined; const point = canvasPoint(mapCanvas, event, mapCellPixels); return inside(active.width, active.height, point) ? point : undefined; }
function makeMapStampAdapter(map: MapDocument) { return { width: map.width, height: map.height, layers: map.layers, collision: map.collision }; }
function useStamp(point: CellPoint, operation: "paint" | "fill" | "rectangle", end?: CellPoint): void { if (!active) return; const stamp = selectedStamp(); if (!stamp) { status.textContent = "先にパレットで素材を選択してください。"; return; } mutateMap(() => { const adapter = makeMapStampAdapter(active!); const result = operation === "paint" ? paintPaletteStamp(adapter, stamp, point, attributeSettings()) : operation === "fill" ? fillPaletteStamp(adapter, stamp, point, attributeSettings()) : rectanglePaletteStamp(adapter, stamp, point, end!, attributeSettings()); if (!result) { status.textContent = operation === "fill" ? "塗りつぶしは単一セルのスタンプだけに使えます。" : "素材がマップ外へ出るため配置しませんでした。"; return; } syncAllComposite(active!); }); }
function markerVisual(): MapMarker["visual"] | undefined { const stamp = selectedStamp(); if (!stamp || stamp.width !== 1 || stamp.height !== 1 || !stamp.cells[0]) return undefined; return { assetId: stamp.cells[0].assetId, frame: stamp.cells[0].frame }; }
function applyMapCell(point: CellPoint): void { if (!active) return; const index = cellIndex(active, point); if (tool.value === "paint") return useStamp(point, "paint"); if (tool.value === "fill") return useStamp(point, "fill"); if (tool.value === "collision-walkable" || tool.value === "collision-blocked") { mutateMap(() => { active!.collision[index] = tool.value === "collision-walkable"; }); return; } if (tool.value === "erase") { mutateMap(() => { active!.layers[layer.value as ManualLayer][index] = null; syncComposite(active!, index); }); return; } if (tool.value === "eyedropper") { const current = active.layers[layer.value as ManualLayer][index]; if (!current) return; const page = ensurePalettePage(); if (!page) return; const matched = page.cells.find((cell) => cell.assetId === current.assetId && cell.frame === current.frame); if (matched) paletteRect = { x: matched.x, y: matched.y, width: 1, height: 1 }; else { palettes.mutate(() => { page.cells = page.cells.filter((cell) => cell.x !== 0 || cell.y !== 0); page.cells.push({ x: 0, y: 0, assetId: current.assetId, frame: current.frame, layer: layer.value as ManualLayer, walkable: active!.collision[index] }); }); paletteRect = { x: 0, y: 0, width: 1, height: 1 }; } render(); return; } if (tool.value === "marker") { const markerKind = marker.value as MapMarkerKind, needsVisual = markerKind === "stairsUp" || markerKind === "stairsDown", visual = markerVisual(); if (needsVisual && !visual) { status.textContent = "階段はパレットから単一セルを選んでから配置してください。"; return; } mutateMap(() => { active!.markers = active!.markers.filter((entry) => entry.kind !== markerKind); addMarker(active!, { id: `${markerKind}-${active!.id}`, kind: markerKind, x: point.x, y: point.y, visual }); }); } }
function download(name: string, value: unknown): void { const link = document.createElement("a"), url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
function createMap(): MapDocument | undefined { const width = Number(mapWidth.value), height = Number(mapHeight.value), size = Number(tileSize.value) as 16 | 32, requestedKind = mapKind.value as "home" | "dungeon"; try { return createManualMap(requestedKind, `${requestedKind === "home" ? "新しい家" : "新しいダンジョン"}`, { width, height, tileSize: size, floor: requestedKind === "home" ? 0 : smallestMissingDungeonFloor(maps) }); } catch (error) { status.textContent = error instanceof Error ? error.message : "マップを作成できません。"; return undefined; } }
async function loadPalettes(): Promise<void> { try { const response = await fetch("/__map-editor/palettes", { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error("palette endpoint unavailable"); const incoming = await response.json(); const errors = validatePaletteLayout(incoming, assets); if (errors.length) throw new Error(errors.join(", ")); palettes.reload(incoming as PaletteLayout); status.textContent = "パレットを再読込しました。"; } catch { palettes.reload(clonePaletteLayout(DEFAULT_PALETTE_LAYOUT as unknown as PaletteLayout)); status.textContent = "標準パレットを読み込みました。"; } selectPageForMap(); render(); }
async function savePalettes(): Promise<void> { if (!import.meta.env.DEV) { download("palettes.json", palettes.layout); status.textContent = "本番版ではパレットJSONを書き出しました。"; return; } try { const response = await fetch("/__map-editor/palettes", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(palettes.layout) }); if (!response.ok) throw new Error(await response.text()); palettes.markSaved(); status.textContent = "パレットを保存しました。"; } catch (error) { status.textContent = `パレット保存エラー: ${error instanceof Error ? error.message : "不明"}`; } render(); }

mapCanvas.onpointerdown = (event) => { const point = mapPoint(event); if (!point) return; mapDragging = true; mapStart = point; if (tool.value !== "rectangle") applyMapCell(point); };
mapCanvas.onpointermove = (event) => { if (!mapDragging || tool.value !== "paint") return; const point = mapPoint(event); if (point) useStamp(point, "paint"); };
mapCanvas.onpointerup = (event) => { if (!mapDragging) return; const end = mapPoint(event); if (tool.value === "rectangle" && mapStart && end) useStamp(mapStart, "rectangle", end); mapDragging = false; mapStart = undefined; render(); };
sourceCanvas.onpointerdown = (event) => { const point = sourcePoint(event); if (!point) return; const selected = sourceRect && point.x >= sourceRect.x && point.x < sourceRect.x + sourceRect.width && point.y >= sourceRect.y && point.y < sourceRect.y + sourceRect.height; sourceDrag = { start: point, moved: false, existing: Boolean(selected) }; if (!selected) sourceRect = { x: point.x, y: point.y, width: 1, height: 1 }; renderSource(); };
sourceCanvas.onpointermove = (event) => { if (!sourceDrag || sourceDrag.existing) return; const point = sourcePoint(event); if (!point) return; sourceDrag.moved = true; sourceRect = paletteRectFromPoints(sourceDrag.start, point); renderSource(); };
sourceCanvas.onpointerup = () => { sourceDrag = undefined; };
paletteCanvas.onpointerdown = (event) => { const point = palettePoint(event); if (!point) return; const current = paletteRect, inSelection = current && point.x >= current.x && point.x < current.x + current.width && point.y >= current.y && point.y < current.y + current.height; paletteDrag = { start: point, moved: false, original: inSelection ? current : undefined }; if (!inSelection) { paletteRect = { x: point.x, y: point.y, width: 1, height: 1 }; renderPalette(); } };
paletteCanvas.onpointermove = (event) => { if (!paletteDrag) return; const point = palettePoint(event); if (!point) return; if (paletteDrag.original) { paletteDrag.moved ||= point.x !== paletteDrag.start.x || point.y !== paletteDrag.start.y; return; } paletteDrag.moved = true; paletteRect = paletteRectFromPoints(paletteDrag.start, point); renderPalette(); };
paletteCanvas.onpointerup = (event) => { const point = palettePoint(event), drag = paletteDrag; paletteDrag = undefined; if (!point || !drag?.original || !drag.moved) return; const page = pageForActiveMap(); if (!page || (point.x === drag.original.x && point.y === drag.original.y)) return; const mode = event.shiftKey ? "copy" : "move"; const success = palettes.mutate(() => { if (!transferPaletteRegion(page, drag.original!, point, mode)) status.textContent = "パレット範囲外へは移動できません。"; }); if (success) { paletteRect = { x: point.x, y: point.y, width: drag.original.width, height: drag.original.height }; render(); } };
document.addEventListener("pointerup", (event) => { if (!sourceDrag || !sourceRect || !sourceAsset()) return; const target = document.elementFromPoint(event.clientX, event.clientY); if (target !== paletteCanvas) { sourceDrag = undefined; return; } const page = ensurePalettePage(), point = palettePoint(event as PointerEvent), asset = sourceAsset(); sourceDrag = undefined; if (!page || !point || !asset) return; const changed = palettes.mutate(() => { if (!placeSourceFrames(page, point, asset, sourceRect!)) status.textContent = "素材範囲がパレット外へ出るため登録しませんでした。"; }); if (changed) { paletteRect = { x: point.x, y: point.y, width: sourceRect.width, height: sourceRect.height }; render(); } });
document.addEventListener("keydown", (event) => { if (event.key !== "Delete" || !paletteRect) return; const page = pageForActiveMap(); if (!page) return; event.preventDefault(); palettes.mutate(() => { page.cells = page.cells.filter((cell) => cell.x < paletteRect!.x || cell.x >= paletteRect!.x + paletteRect!.width || cell.y < paletteRect!.y || cell.y >= paletteRect!.y + paletteRect!.height); }); render(); });

kind.onchange = () => { const candidate = maps.filter((map) => map.kind === kind.value).sort((a, b) => a.floor - b.floor)[0]; if (candidate) setActive(candidate); else render(); };
layer.onchange = render; zoom.onchange = render; grid.onchange = render; pass.onchange = render; attributeMode.onchange = render;
assetSelect.onchange = () => { selectedAssetId = assetSelect.value; sourceRect = undefined; renderSource(); };
q<HTMLButtonElement>("[data-action=apply-map-settings]").onclick = () => { if (!active) return; const width = Number(mapWidth.value), height = Number(mapHeight.value), requestedSize = Number(tileSize.value) as 16 | 32, requestedKind = mapKind.value as "home" | "dungeon"; mutateMap(() => { const result = applyMapSettingsAtomically(active!, { width, height, tileSize: requestedSize, kind: requestedKind, maps }); if (!result.ok) status.textContent = result.reason; }); kind.value = active.kind; mapKind.value = active.kind; mapWidth.value = String(active.width); mapHeight.value = String(active.height); tileSize.value = String(active.tileSize); selectPageForMap(); updateMarkerOptions(); render(); };
q<HTMLButtonElement>("[data-action=undo]").onclick = async () => { if (!active) return; const history = historyFor(active), previous = history.undo.pop(); if (!previous) return; history.redo.push(mapSnapshot()); active = previous; await saveActive(); selectPageForMap(); render(); };
q<HTMLButtonElement>("[data-action=redo]").onclick = async () => { if (!active) return; const history = historyFor(active), next = history.redo.pop(); if (!next) return; history.undo.push(mapSnapshot()); active = next; await saveActive(); selectPageForMap(); render(); };
q<HTMLButtonElement>("[data-action=new]").onclick = async () => { const next = createMap(); if (!next) return; maps.push(next); await repository.save(next); setActive(next); status.textContent = next.kind === "dungeon" ? `最小の欠番である第${next.floor}階を作成しました。` : "家マップを作成しました。"; };
q<HTMLButtonElement>("[data-action=rename]").onclick = () => { if (!active) return; const name = prompt("マップ名", active.name); if (name?.trim()) mutateMap(() => { active!.name = name.trim(); }); };
q<HTMLButtonElement>("[data-action=duplicate]").onclick = async () => { if (!active) return; const copy = cloneMap(active); try { copy.floor = copy.kind === "home" ? 0 : smallestMissingDungeonFloor(maps); } catch (error) { status.textContent = error instanceof Error ? error.message : "階番号を割り当てられません。"; return; } copy.id = uniqueId("map"); copy.name += " コピー"; copy.createdAt = new Date().toISOString(); copy.updatedAt = copy.createdAt; copy.markers = copy.markers.map((entry) => ({ ...entry, id: `${entry.kind}-${copy.id}` })); maps.push(copy); await repository.save(copy); status.textContent = copy.kind === "dungeon" ? `欠番の第${copy.floor}階として複製しました。` : "家マップを複製しました。"; setActive(copy); };
q<HTMLButtonElement>("[data-action=delete]").onclick = async () => { if (!active) return; const deleting = active, hasLaterFloors = deleting.kind === "dungeon" && maps.some((map) => map.kind === "dungeon" && map.floor > deleting.floor), message = hasLaterFloors ? `「${deleting.name}」（第${deleting.floor}階）を削除しますか？\n後続階は自動的に詰められ、階段の接続先も新しい階番号に変わります。` : `「${deleting.name}」を削除しますか？`; if (!confirm(message)) return; const remaining = maps.filter((map) => map.id !== deleting.id); let floorUpdates: ReturnType<typeof planDungeonFloorCompaction>; try { floorUpdates = planDungeonFloorCompaction(remaining); } catch (error) { status.textContent = error instanceof Error ? error.message : "階番号を整理できません。"; return; } applyDungeonFloorUpdates(remaining, floorUpdates); await repository.delete(deleting.id); maps = remaining; for (const update of floorUpdates) { const map = maps.find((value) => value.id === update.id); if (map) await repository.save(map); } const next = maps.find((map) => map.kind === kind.value) ?? maps[0]; if (next) { setActive(next); status.textContent = floorUpdates.length ? `${deleting.name}を削除し、後続階を詰めました。階段接続は新しい連続階に従います。` : `${deleting.name}を削除しました。`; } else { const created = createMap(); if (created) { maps = [created]; await repository.save(created); setActive(created); } } };
q<HTMLButtonElement>("[data-action=export-map]").onclick = () => { if (active) download(`${active.id}.json`, active); };
q<HTMLButtonElement>("[data-action=export-pack]").onclick = () => download("map-pack.json", { version: 5, maps });
q<HTMLButtonElement>("[data-action=try]").onclick = () => { const home = maps.find((map) => map.kind === "home"), dungeons = maps.filter((map) => map.kind === "dungeon").sort((a, b) => a.floor - b.floor); if (!home) return; const pack = { home, dungeons }, issues = validateTrialMapPack(pack); if (issues.length) { status.textContent = `試遊できません: ${issues.join(", ")}`; render(); return; } storeTrialMapPack(pack); window.location.href = "./?autostart=world"; };
q<HTMLButtonElement>("[data-action=palette-add]").onclick = () => { if (!active) return; const id = uniqueId("palette"); palettes.mutate((layout) => addPalettePage(layout, createPalettePage({ id, label: "新しいパレット", mapKind: active!.kind, tileSize: active!.tileSize, width: 8, height: 8 }))); activePageId = id; paletteRect = undefined; render(); };
q<HTMLButtonElement>("[data-action=palette-rename]").onclick = () => { const page = activePage(); if (!page) return; const label = prompt("パレット名", page.label); if (label) palettes.mutate(() => { if (!renamePalettePage(page, label)) status.textContent = "名前を入力してください。"; }); render(); };
q<HTMLButtonElement>("[data-action=palette-resize]").onclick = () => { const page = activePage(); if (!page) return; const width = Number(prompt("幅（1〜256）", String(page.width))), height = Number(prompt("高さ（1〜256）", String(page.height))); palettes.mutate(() => { const result = resizePalettePage(page, width, height); if (!result.ok) status.textContent = result.reason; }); render(); };
q<HTMLButtonElement>("[data-action=palette-delete]").onclick = () => { const page = activePage(); if (!page) return; if (palettes.layout.pages.length <= 1) { status.textContent = "最後のパレットページは削除できません。保存可能なページを1つ残してください。"; render(); return; } if (!confirm(`パレット「${page.label}」を削除しますか？`)) return; palettes.mutate((layout) => { deletePalettePage(layout, page.id); }); selectPageForMap(); render(); };
q<HTMLButtonElement>("[data-action=palette-undo]").onclick = () => { palettes.undo(); selectPageForMap(); render(); };
q<HTMLButtonElement>("[data-action=palette-redo]").onclick = () => { palettes.redo(); selectPageForMap(); render(); };
q<HTMLButtonElement>("[data-action=palette-save]").onclick = () => { void savePalettes(); };
q<HTMLButtonElement>("[data-action=palette-reload]").onclick = () => { void loadPalettes(); };
q<HTMLButtonElement>("[data-action=palette-export]").onclick = () => download("palettes.json", palettes.layout);
importInput.onchange = async () => { const file = importInput.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()) as { maps?: unknown[] }; const incoming = (Array.isArray(parsed.maps) ? parsed.maps : [parsed]).map(normalizeMap); for (const value of incoming) { maps = maps.some((map) => map.id === value.id) ? maps.map((map) => map.id === value.id ? value : map) : [...maps, value]; await repository.save(value); } if (incoming[0]) setActive(incoming[0]); status.textContent = `${incoming.length}件を読み込みました。`; } catch (error) { status.textContent = `読み込みエラー: ${error instanceof Error ? error.message : "不正なJSON"}`; } };
void (async () => { maps = await repository.list(); if (!maps.length) { const home = createManualMap("home", "新しい家", { width: 32, height: 20, tileSize: 16, floor: 0 }), dungeon = createManualMap("dungeon", "新しいダンジョン", { width: 48, height: 36, tileSize: 16, floor: 1 }); maps = [home, dungeon]; await repository.save(home); await repository.save(dungeon); } setActive(maps.find((map) => map.kind === "home") ?? maps[0]!); await loadPalettes(); })();
