/* AUTO-GENERATED by scripts/build-actor-assets.mjs. Do not edit. */
import type { ActorSettingsCatalog } from "./actorSettings";
export const GENERATED_ACTOR_SETTINGS: ActorSettingsCatalog = {
  "version": 1,
  "actors": {}
};
