/* AUTO-GENERATED by scripts/build-actor-assets.mjs. Do not edit. */
import type { CraftpixActorDefinition } from "./craftpixActors";
export const GENERATED_ACTORS: readonly CraftpixActorDefinition[] = [];
