/* AUTO-GENERATED by scripts/build-actor-assets.mjs. Do not edit. */
import type { ActorSettingsCatalog } from "./actorSettings";
export const GENERATED_ACTOR_SETTINGS: ActorSettingsCatalog = {
  "version": 1,
  "actors": {
    "citizen2": {
      "label": "商人",
      "roles": [
        "player"
      ],
      "archetype": "brute",
      "tier": 1
    }
  }
};
