import type { Customer, ItemDefinition, ItemCategory, Quest } from "./types";

const specs: Array<[string, ItemCategory, string, string, string, number, 1 | 2 | 3, string, boolean?, string?]> = [
  ["rusted-sword", "weapon", "古い剣", "古い騎士剣らしい", "王国軍旧式剣", 260, 2, "刃に消えない血痕がある。", false, "duke"],
  ["black-sword", "weapon", "黒い長剣", "由来不明の黒剣", "黒騎士アルベルトの呪剣", 3200, 3, "光をほとんど反射しない、冷たい長剣。", true, "duke"],
  ["silver-wolf", "weapon", "銀の剣", "狼紋の剣", "銀狼騎士団の儀礼剣", 1800, 2, "柄頭に銀狼の紋章がある。", true, "duke"],
  ["bronze-spear", "weapon", "青銅の槍", "古い儀礼槍", "峡谷王朝の祭礼槍", 620, 3, "穂先に青い錆が浮く。", false, "duke"],
  ["notched-dagger", "weapon", "欠けた短剣", "盗賊の短剣らしい", "夜鴉団の合図短剣", 190, 1, "柄に羽根の刻印がある。", false, "duke"],
  ["amber-wand", "arcane", "琥珀の杖", "魔力を帯びた杖", "雷鳴術師の導杖", 1450, 2, "杖の中で小さな火花が揺れる。", true, "mage"],
  ["cracked-orb", "arcane", "ひび割れた珠", "魔力を帯びた珠", "月読の観測珠", 900, 1, "中に霧のような光がある。", false, "mage"],
  ["smoke-vial", "arcane", "曇った小瓶", "煙術の触媒", "夜隠しの錬金触媒", 380, 1, "振ると黒い煙が底を這う。", false, "mage"],
  ["rune-key", "arcane", "刻印鍵", "封印を解く鍵らしい", "深層門のルーン鍵", 1100, 1, "鍵歯が文字のように並ぶ。", false, "mage"],
  ["moon-charm", "arcane", "月の護符", "月魔術の護符", "眠り守りの月環", 720, 1, "持つと少しだけ温かい。", false, "mage"],
  ["old-ring", "relic", "古びた指輪", "北方の貴族指輪らしい", "冬塔家の誓約環", 1250, 1, "内側に読めない文字がある。", true, "scholar"],
  ["stone-statue", "relic", "小さな石像", "古代祭祀の像", "地下王朝の門番像", 1560, 3, "片目だけが赤い石でできている。", true, "scholar"],
  ["broken-tablet", "relic", "割れた石板", "古代文字の石板", "エストラ王朝の税記録", 800, 3, "半分だけ文字が残っている。", false, "scholar"],
  ["sun-idol", "relic", "金色の像", "太陽信仰の像", "暁神殿の祈祷像", 2300, 2, "底に灰がこびりつく。", false, "scholar"],
  ["sealed-box", "relic", "封じられた箱", "古代の保管箱", "王墓の副葬箱", 1900, 3, "どの鍵穴にも合わない。", false, "scholar"],
  ["tiger-eye", "gem", "縞模様の石", "虎目石らしい", "夕陽の虎眼石", 460, 1, "光の角度で金色に揺れる。", false, "jeweler"],
  ["blue-gem", "gem", "青い宝石", "海色のサファイア", "深海王の涙", 2100, 1, "内部に泡のような傷がある。", true, "jeweler"],
  ["rough-opal", "gem", "乳白色の石", "粗いオパール", "夢見の遊色石", 980, 1, "見る人ごとに色が変わる。", false, "jeweler"],
  ["black-pearl", "gem", "黒い真珠", "希少な黒真珠", "嵐海の黒珠", 1350, 1, "わずかに潮の香りがする。", false, "jeweler"],
  ["red-crystal", "gem", "赤い結晶", "炎の結晶", "火竜脈の紅晶", 780, 1, "握ると掌が熱くなる。", false, "jeweler"],
  ["torn-grimoire", "book", "破れた本", "失われた魔導書の一頁", "星巡りの魔導書・第一頁", 1700, 1, "余白に星図が描かれている。", true, "mage"],
  ["travel-journal", "book", "古い日誌", "冒険者の日誌", "第一遠征隊の踏査記録", 530, 1, "最後の頁だけ濡れている。", false, "scholar"],
  ["poetry-scroll", "book", "巻物", "宮廷詩集らしい", "灰冠王の恋歌集", 690, 1, "読めないほど細い字で書かれている。", false, "scholar"],
  ["codex-leaf", "book", "奇妙な紙片", "古代語の紙片", "深層地図の断片", 1000, 1, "端に階段の印がある。", false, "scholar"],
  ["mosaic-panel", "art", "色ガラス片", "宗教画の断片", "沈没礼拝堂のモザイク", 860, 2, "青いガラスに人物の目が描かれる。", false, "jeweler"],
  ["masked-portrait", "art", "小さな肖像画", "貴族の肖像らしい", "仮面侯の肖像", 1480, 2, "見るたびに表情が違って見える。", true, "duke"],
  ["ivory-carving", "art", "象牙の彫刻", "古い装飾彫刻", "月桂宮の鳥籠飾り", 740, 1, "鳥の瞳に黒い宝石がある。", false, "jeweler"],
  ["bronze-mask", "art", "青銅の仮面", "古い葬送面", "砂漠王の葬送面", 1650, 2, "裏面に乾いた花が貼られている。", false, "scholar"],
  ["amber-frame", "art", "琥珀の額縁", "虫入りの琥珀額", "眠らぬ蛾の琥珀標本", 930, 1, "中の蛾がわずかに羽ばたく。", false, "jeweler"],
  ["slime-core", "material", "透明な塊", "魔物の核", "深青スライムの魔核", 200, 1, "光にかざすと脈打つ。", false, "mage"],
  ["moon-fungus", "material", "白い茸", "月光茸", "夜照らし茸", 170, 1, "暗所で淡く光る。", false, "merchant"],
  ["beast-claw", "material", "大きな爪", "洞窟獣の爪", "岩穿ち獣の爪", 260, 1, "石の粉が付着している。", false, "merchant"],
  ["silk-thread", "material", "銀の糸", "魔蛛の糸", "月糸蜘蛛の吐糸", 430, 1, "切れずに冷たい。", false, "mage"],
  ["ember-scale", "material", "赤い鱗", "火蜥蜴の鱗", "溶岩蜥蜴の逆鱗", 620, 1, "角度で炎の色が走る。", false, "mage"],
  ["herb", "material", "薬草", "傷薬になる薬草", "銀露草", 50, 1, "葉先に銀色の露が残る。", false, "merchant"],
  ["adventurer-badge", "relic", "古い徽章", "冒険者の認識票", "第二遠征隊の隊章", 310, 1, "裏に名前が刻まれている。", false, "merchant"],
  ["bone-flute", "art", "骨の笛", "儀礼用の笛", "峡谷民の送魂笛", 510, 1, "吹くと音が吸い込まれる。", false, "scholar"],
  ["coral-crown", "gem", "珊瑚の冠", "海民の冠飾り", "潮王女の珊瑚冠", 1750, 2, "塩をふくと淡く歌う。", false, "jeweler"],
  ["brass-compass", "relic", "真鍮の方位器", "古い方位器", "迷宮測量士の羅針盤", 1060, 1, "針が北を指さない。", false, "scholar"],
  ["glass-feather", "arcane", "ガラスの羽", "風術の触媒", "風渡り鳥の結晶羽", 810, 1, "空中でゆっくり回転する。", false, "mage"],
];

export const ITEM_DEFINITIONS: Record<string, ItemDefinition> = Object.fromEntries(
  specs.map(([id, category, unknownName, suspectedName, trueName, baseValue, bulk, description, unique, preferredBuyer]) => [
    id,
    { id, category, unknownName, suspectedName, trueName, baseValue, bulk, description, unique, preferredBuyer },
  ]),
);

export const CUSTOMERS: Customer[] = [
  { id: "merchant", name: "ミラ", title: "町の道具商", interests: ["material", "weapon"], budget: 650, relation: 0, knowledge: ["material"], color: 0x8fc6a5 },
  { id: "duke", name: "ローデン", title: "剣好きの公爵", interests: ["weapon", "art"], budget: 7200, relation: 0, knowledge: ["weapon"], color: 0xb9a5eb },
  { id: "scholar", name: "エリス", title: "古代研究者", interests: ["relic", "book"], budget: 3400, relation: 0, knowledge: ["relic", "book"], color: 0xf0cf83 },
  { id: "mage", name: "ネヴァ", title: "魔法使い", interests: ["arcane", "book", "material"], budget: 5000, relation: 0, knowledge: ["arcane", "book"], color: 0x92b8ea },
  { id: "jeweler", name: "サフィ", title: "宝石収集家", interests: ["gem", "art"], budget: 4600, relation: 0, knowledge: ["gem", "art"], color: 0xe58eb1 },
];

export const INITIAL_QUESTS: Quest[] = [
  { id: "herb", title: "銀露草の回収", description: "入口付近で薬草を見つけて持ち帰る。", status: "active", targetItemId: "herb", targetFloor: 1 },
  { id: "lost-sword", title: "落とした剣", description: "冒険者の落とし物を探す。", status: "available", targetItemId: "rusted-sword", targetFloor: 1 },
  { id: "missing", title: "帰らない冒険者", description: "地下で遺品を探す。", status: "available", targetItemId: "adventurer-badge", targetFloor: 2 },
  { id: "old-ring", title: "古びた指輪", description: "誰に見せるべきか考える。", status: "available", targetItemId: "old-ring", targetFloor: 2 },
  { id: "black-sword", title: "黒い長剣の噂", description: "地下深くで、光を吸うような黒い剣が見つかったらしい。", status: "available", targetItemId: "black-sword", targetFloor: 3 },
  { id: "black-tomb", title: "黒騎士の墓所", description: "呪いの手掛かりを、地下の墓所で探す。", status: "available", targetFloor: 3 },
  { id: "grimoire", title: "失われた魔導書", description: "星図のある紙片を探す。", status: "available", targetItemId: "torn-grimoire", targetFloor: 3 },
  { id: "statue", title: "門番像の調査", description: "片目の赤い石像を探す。", status: "available", targetItemId: "stone-statue", targetFloor: 4 },
  { id: "jewel", title: "深海の涙", description: "青い宝石の出所を知りたい客がいる。", status: "available", targetItemId: "blue-gem", targetFloor: 4 },
  { id: "delivery", title: "地下の配達", description: "冒険者へ薬草を届ける。", status: "available", targetFloor: 2 },
  { id: "compass", title: "迷宮測量士の羅針盤", description: "北を指さない羅針盤を探す。", status: "available", targetItemId: "brass-compass", targetFloor: 5 },
  { id: "silver-wolf", title: "銀狼の剣", description: "公爵が探す儀礼剣の噂を追う。", status: "available", targetItemId: "silver-wolf", targetFloor: 5 },
  { id: "mask", title: "砂漠王の葬送面", description: "古代の仮面を探す。", status: "available", targetItemId: "bronze-mask", targetFloor: 6 },
  { id: "crown", title: "潮王女の珊瑚冠", description: "海の伝承に残る冠を探す。", status: "available", targetItemId: "coral-crown", targetFloor: 7 },
  { id: "deep-map", title: "深層地図の断片", description: "最深部への道を示す紙片を集める。", status: "available", targetItemId: "codex-leaf", targetFloor: 8 },
];
