// Generated by scripts/build-shop-art.mjs.
export const ITEM_ART: Record<string, {label: string; review: string; sourceCell: number; frameSize: number; bounds: {x: number; y: number; width: number; height: number}}> = {
  "iron-sword": {
    "label": "鉄の剣",
    "review": "灰色の鋼の直剣",
    "sourceCell": 0,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 17,
      "height": 18
    }
  },
  "bronze-spear": {
    "label": "青銅の槍",
    "review": "青銅の穂先と長い柄",
    "sourceCell": 1,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 15,
      "height": 18
    }
  },
  "nameless-black-blade": {
    "label": "名もなき黒剣",
    "review": "黒い刃と紫の縁",
    "sourceCell": 2,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 16,
      "height": 18
    }
  },
  "leather-armor": {
    "label": "革鎧",
    "review": "茶色の胴鎧",
    "sourceCell": 3,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 16,
      "height": 18
    }
  },
  "iron-helmet": {
    "label": "鉄兜",
    "review": "銀灰色の兜",
    "sourceCell": 4,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 15,
      "height": 18
    }
  },
  "round-shield": {
    "label": "円盾",
    "review": "金属縁の丸い木盾",
    "sourceCell": 5,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 17,
      "height": 18
    }
  },
  "minor-healing-potion": {
    "label": "小回復薬",
    "review": "小さい丸瓶の赤い薬",
    "sourceCell": 6,
    "frameSize": 32,
    "bounds": {
      "x": 9,
      "y": 7,
      "width": 13,
      "height": 18
    }
  },
  "major-healing-potion": {
    "label": "大回復薬",
    "review": "金の帯がある大きい角瓶の赤い薬",
    "sourceCell": 7,
    "frameSize": 32,
    "bounds": {
      "x": 9,
      "y": 7,
      "width": 14,
      "height": 18
    }
  },
  "antidote": {
    "label": "毒消し",
    "review": "葉の栓と緑色の薬",
    "sourceCell": 8,
    "frameSize": 32,
    "bounds": {
      "x": 10,
      "y": 7,
      "width": 11,
      "height": 18
    }
  },
  "moon-fungus": {
    "label": "月光茸",
    "review": "青く光る傘と白い柄の茸",
    "sourceCell": 9,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 15,
      "height": 18
    }
  },
  "slime-core": {
    "label": "スライムの核",
    "review": "透明な青緑の膜と中央の核",
    "sourceCell": 10,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 8,
      "width": 18,
      "height": 17
    }
  },
  "beast-claw": {
    "label": "洞窟獣の爪",
    "review": "湾曲した黒い爪",
    "sourceCell": 11,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 17,
      "height": 18
    }
  },
  "old-ring": {
    "label": "古い指輪",
    "review": "古びた銀の輪",
    "sourceCell": 12,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 17,
      "height": 18
    }
  },
  "blue-gem": {
    "label": "青い宝石",
    "review": "深い青色の多面体",
    "sourceCell": 13,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 17,
      "height": 18
    }
  },
  "rune-tablet": {
    "label": "ルーン石板",
    "review": "刻印を持つ灰色の石板",
    "sourceCell": 14,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 16,
      "height": 18
    }
  },
  "field-flask": {
    "label": "携行薬瓶",
    "review": "革巻きの赤い携行瓶",
    "sourceCell": 15,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 16,
      "height": 18
    }
  },
  "elixir": {
    "label": "秘薬",
    "review": "細身の紫色の薬瓶",
    "sourceCell": 16,
    "frameSize": 32,
    "bounds": {
      "x": 11,
      "y": 7,
      "width": 9,
      "height": 18
    }
  },
  "grand-elixir": {
    "label": "霊薬",
    "review": "白と金の装飾瓶",
    "sourceCell": 17,
    "frameSize": 32,
    "bounds": {
      "x": 10,
      "y": 7,
      "width": 11,
      "height": 18
    }
  },
  "herb": {
    "label": "薬草",
    "review": "茎で束ねた緑の葉",
    "sourceCell": 18,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 15,
      "height": 18
    }
  },
  "iron-ore": {
    "label": "鉄鉱石",
    "review": "錆色の鉄を含む灰色の岩",
    "sourceCell": 19,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 8,
      "width": 18,
      "height": 17
    }
  },
  "silver-ore": {
    "label": "銀鉱",
    "review": "白銀の鉱脈が走る暗い岩",
    "sourceCell": 20,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 18,
      "height": 18
    }
  },
  "gold-ore": {
    "label": "金鉱",
    "review": "金色の鉱脈が走る暗い岩",
    "sourceCell": 21,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 18,
      "height": 18
    }
  },
  "mithril": {
    "label": "ミスリル",
    "review": "氷青色の金属塊",
    "sourceCell": 22,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 17,
      "height": 18
    }
  },
  "orichalcum": {
    "label": "オリハルコン",
    "review": "赤銅色の金属塊",
    "sourceCell": 23,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 16,
      "height": 18
    }
  },
  "mana-stone": {
    "label": "魔石",
    "review": "紫色の発光結晶",
    "sourceCell": 24,
    "frameSize": 32,
    "bounds": {
      "x": 9,
      "y": 7,
      "width": 13,
      "height": 18
    }
  },
  "diamond": {
    "label": "ダイアモンド",
    "review": "透明な白いカット宝石",
    "sourceCell": 25,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 9,
      "width": 18,
      "height": 16
    }
  },
  "cloth-wrap": {
    "label": "風呂敷",
    "review": "藍色の布の結び包み",
    "sourceCell": 26,
    "frameSize": 32,
    "bounds": {
      "x": 8,
      "y": 7,
      "width": 16,
      "height": 18
    }
  },
  "shoulder-sack": {
    "label": "背負い袋",
    "review": "一本の肩紐のある麻袋",
    "sourceCell": 27,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 9,
      "width": 14,
      "height": 16
    }
  },
  "pedlar-case": {
    "label": "行商箱",
    "review": "革帯付きの木箱",
    "sourceCell": 28,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 11,
      "width": 18,
      "height": 14
    }
  },
  "caravan-pack": {
    "label": "隊商荷駄",
    "review": "毛布と左右の荷物付き大型荷駄",
    "sourceCell": 29,
    "frameSize": 32,
    "bounds": {
      "x": 7,
      "y": 7,
      "width": 17,
      "height": 18
    }
  }
};
