/* AUTO-GENERATED by scripts/build-map-tile-assets.mjs. Do not edit. */
export const MAP_ASSET_CATALOG = [
  {
    "id": "dungeon.floor",
    "label": "ダンジョンの床",
    "tileSize": 16,
    "margin": 0,
    "spacing": 0,
    "columns": 1,
    "rows": 1,
    "frameCount": 1,
    "mapKinds": [
      "dungeon"
    ],
    "defaultLayer": "ground",
    "defaultWalkable": true,
    "path": "/assets/map-tiles/generated/dungeon.floor.png"
  },
  {
    "id": "dungeon.stairs-down",
    "label": "下り階段",
    "tileSize": 16,
    "margin": 0,
    "spacing": 0,
    "columns": 1,
    "rows": 1,
    "frameCount": 1,
    "mapKinds": [
      "dungeon"
    ],
    "defaultLayer": "decoration",
    "defaultWalkable": true,
    "path": "/assets/map-tiles/generated/dungeon.stairs-down.png"
  },
  {
    "id": "dungeon.stairs-up",
    "label": "上り階段",
    "tileSize": 16,
    "margin": 0,
    "spacing": 0,
    "columns": 1,
    "rows": 1,
    "frameCount": 1,
    "mapKinds": [
      "dungeon"
    ],
    "defaultLayer": "decoration",
    "defaultWalkable": true,
    "path": "/assets/map-tiles/generated/dungeon.stairs-up.png"
  },
  {
    "id": "dungeon.wall",
    "label": "ダンジョンの壁",
    "tileSize": 16,
    "margin": 0,
    "spacing": 0,
    "columns": 4,
    "rows": 4,
    "frameCount": 16,
    "mapKinds": [
      "dungeon"
    ],
    "defaultLayer": "structure",
    "defaultWalkable": false,
    "path": "/assets/map-tiles/generated/dungeon.wall.png"
  },
  {
    "id": "home.floor",
    "label": "家の床",
    "tileSize": 16,
    "margin": 0,
    "spacing": 0,
    "columns": 1,
    "rows": 1,
    "frameCount": 1,
    "mapKinds": [
      "home"
    ],
    "defaultLayer": "ground",
    "defaultWalkable": true,
    "path": "/assets/map-tiles/generated/home.floor.png"
  },
  {
    "id": "home.wall",
    "label": "家の壁",
    "tileSize": 16,
    "margin": 0,
    "spacing": 0,
    "columns": 4,
    "rows": 4,
    "frameCount": 16,
    "mapKinds": [
      "home"
    ],
    "defaultLayer": "structure",
    "defaultWalkable": false,
    "path": "/assets/map-tiles/generated/home.wall.png"
  }
] as const;
export const MAP_ASSET_IDS = MAP_ASSET_CATALOG.map((asset) => asset.id);
export const DEFAULT_PALETTE_LAYOUT = {
  "version": 1,
  "pages": [
    {
      "id": "home-default",
      "label": "家・基本",
      "mapKind": "home",
      "tileSize": 16,
      "width": 4,
      "height": 4,
      "cells": [
        {
          "x": 0,
          "y": 0,
          "assetId": "home.floor",
          "frame": 0,
          "layer": "ground",
          "walkable": true
        },
        {
          "x": 1,
          "y": 0,
          "assetId": "home.wall",
          "frame": 0,
          "layer": "structure",
          "walkable": false
        }
      ]
    },
    {
      "id": "dungeon-default",
      "label": "ダンジョン・基本",
      "mapKind": "dungeon",
      "tileSize": 16,
      "width": 4,
      "height": 4,
      "cells": [
        {
          "x": 0,
          "y": 0,
          "assetId": "dungeon.floor",
          "frame": 0,
          "layer": "ground",
          "walkable": true
        },
        {
          "x": 1,
          "y": 0,
          "assetId": "dungeon.wall",
          "frame": 0,
          "layer": "structure",
          "walkable": false
        },
        {
          "x": 2,
          "y": 0,
          "assetId": "dungeon.stairs-up",
          "frame": 0,
          "layer": "decoration",
          "walkable": true
        },
        {
          "x": 3,
          "y": 0,
          "assetId": "dungeon.stairs-down",
          "frame": 0,
          "layer": "decoration",
          "walkable": true
        }
      ]
    }
  ]
} as const;
