import { describe, expect, it } from "vitest";
import { addMarker, cloneMap, compileMap, copyMapFragment, createBlankMap, createManualMap, eraseTile, fillMap, mapIndex, MapRepository, normalizeMap, pasteMapFragment, placeManualTile, placeTile, resizeMap, setMapTileSize, validateMap } from "./mapDocument";
describe("MapDocument v6", () => {
  it("creates blank dimensions with explicit collision and visual layers", () => { const map=createBlankMap("home"); expect([map.version,map.width,map.height]).toEqual([6,32,20]); expect(map.terrain.every((x)=>x===null)).toBe(true); expect(map.collision).toHaveLength(32*20); expect(map.layers.ground).toHaveLength(32*20); expect(map.enemyRoster).toEqual([]); });
  it("places, erases, clones and compiles", () => { const map=createBlankMap("dungeon"); placeTile(map,1,1,"dungeon.floor"); expect(map.terrain[mapIndex(map,1,1)]).toBe("dungeon.floor"); const copy=cloneMap(map); eraseTile(copy,1,1); expect(map.terrain[mapIndex(map,1,1)]).toBe("dungeon.floor"); expect(compileMap(map).tiles[1][1]).toBe(0); });
  it("reports invalid map-kind tiles", () => { const map=createBlankMap("home"); map.terrain[0]="dungeon.wall"; expect(validateMap(map)).toContain("invalid tile"); });
  it("flood fills only the connected source region", () => { const map=createBlankMap("home"); placeTile(map,0,0,"home.wall"); placeTile(map,1,0,"home.wall"); placeTile(map,0,1,"home.wall"); placeTile(map,4,4,"home.wall"); fillMap(map,0,0,"home.floor"); expect(map.terrain[0]).toBe("home.floor"); expect(map.terrain[4*map.width+4]).toBe("home.wall"); });
  it("copies and pastes a rectangular fragment", () => { const map=createBlankMap("home"); placeTile(map,1,1,"home.floor"); placeTile(map,2,1,"home.wall"); const fragment=copyMapFragment(map,1,1,2,1); const target=createBlankMap("home"); expect(pasteMapFragment(target,fragment,5,5)).toBe(true); expect(target.terrain[5*target.width+5]).toBe("home.floor"); expect(target.terrain[5*target.width+6]).toBe("home.wall"); });
  it("accepts draft structure without requiring markers", async () => { const map=createBlankMap("home"); const repository=new MapRepository(); await repository.save(map); expect(normalizeMap(map).markers).toEqual([]); });
  it("compiles canonical up/down markers with dedicated fallback visuals", () => { const map=createBlankMap("dungeon"); for(let y=1;y<4;y++)for(let x=1;x<4;x++)placeTile(map,x,y,"dungeon.floor"); addMarker(map,{id:"up",kind:"stairsUp",x:1,y:1}); addMarker(map,{id:"down",kind:"stairsDown",x:2,y:2}); const compiled=compileMap(map); expect(compiled.stairsUp).toEqual({x:1,y:1}); expect(compiled.stairsDown).toEqual({x:2,y:2}); expect(compiled.stairsUpVisual).toEqual({assetId:"dungeon.stairs-up",frame:0}); expect(compiled.stairsDownVisual).toEqual({assetId:"dungeon.stairs-down",frame:0}); });
  it("rejects unknown input with an explicit error", () => { expect(() => normalizeMap(null)).toThrow(/MapDocument v3/); });
  it("reports missing markers", () => { const map=createBlankMap("home"); expect(validateMap(map)).toEqual(expect.arrayContaining(["marker homeSpawn","marker dungeonEntrance"])); });
  it.each(["dungeonEntrance", "homeStorage", "homePreparation", "homeVisitors"] as const)("reports an isolated %s marker", (isolatedKind) => {
    const map = createManualMap("home", { width: 7, height: 7 });
    map.collision.fill(true);
    const markerPositions = {
      homeSpawn: { x: 1, y: 1 },
      dungeonEntrance: { x: 5, y: 1 },
      homeStorage: { x: 1, y: 5 },
      homePreparation: { x: 3, y: 5 },
      homeVisitors: { x: 5, y: 5 },
    } as const;
    Object.entries(markerPositions).forEach(([kind, position]) => addMarker(map, { id: kind, kind: kind as keyof typeof markerPositions, ...position }));
    const isolated = markerPositions[isolatedKind];
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) map.collision[mapIndex(map, isolated.x + dx, isolated.y + dy)] = false;
    expect(validateMap(map)).toContain(`marker ${isolatedKind} unreachable`);
  });
  it("stores a selected frame and explicit collision without neighbour-based changes", () => { const map=createBlankMap("dungeon"); map.terrain.fill("dungeon.floor"); placeManualTile(map,1,1,"dungeon.wall","structure",7); placeManualTile(map,2,1,"dungeon.wall","structure",3); map.collision = map.terrain.map((id) => id === "dungeon.floor"); const compiled = compileMap(map); expect(map.layers.structure[mapIndex(map,1,1)]).toEqual({ assetId:"dungeon.wall", frame:7 }); expect(map.layers.structure[mapIndex(map,2,1)]).toEqual({ assetId:"dungeon.wall", frame:3 }); expect(compiled.tiles[1]?.[1]).toBe(1); expect(compiled.authoredLayers?.structure?.[mapIndex(map,1,1)]).toEqual({ assetId:"dungeon.wall", frame:7 }); });
  it("clears compatibility terrain when the last manual layer is erased", () => { const map=createManualMap("home",{width:4,height:4}); placeManualTile(map,1,1,"home.floor","ground",0); const index=mapIndex(map,1,1); expect(map.terrain[index]).toBe("home.floor"); placeManualTile(map,1,1,null,"ground"); expect(map.layers.ground[index]).toBeNull(); expect(map.terrain[index]).toBeNull(); });
  it("provides explicit layers for a fresh manual document", () => { const map = createManualMap("home"); expect(map.collision).toHaveLength(map.width * map.height); expect(map.layers?.ground).toHaveLength(map.width * map.height); });
  it("treats collision as the movement source of truth", () => { const map = createManualMap("dungeon"); map.terrain[0] = "dungeon.wall"; map.collision![0] = true; expect(compileMap(map).tiles[0]?.[0]).toBe(0); });
  it("resizes from the top-left and refuses to discard data", () => { const map=createManualMap("home",{width:5,height:5}); placeManualTile(map,4,4,"home.floor"); expect(resizeMap(map,5,6)).toEqual({ok:true}); expect(resizeMap(map,4,4)).toMatchObject({ok:false}); eraseTile(map,4,4); expect(resizeMap(map,4,4)).toEqual({ok:true}); expect(map.width).toBe(4); });
  it("only changes tile size on an empty map", () => { const map=createManualMap("home",{width:4,height:4}); expect(setMapTileSize(map,32)).toEqual({ok:true}); placeTile(map,1,1,"home.floor"); expect(setMapTileSize(map,16)).toMatchObject({ok:false}); });
  it("keeps a dungeon enemy roster in the compiled runtime map and rejects it on home maps", () => { const dungeon=createManualMap("dungeon",{width:4,height:4}); dungeon.enemyRoster=["slime1"]; expect(compileMap(dungeon).enemyRoster).toEqual(["slime1"]); const home=createManualMap("home",{width:4,height:4}); home.enemyRoster=["slime1"]; expect(validateMap(home)).toContain("home enemy roster"); });
  it("migrates v3 terrain, dungeonReturn, and stairs to canonical v6 markers", () => { const old:any={...createManualMap("dungeon",{width:4,height:4}),version:3,tileSize:16,tileFrames:Array(16).fill(0),layers:{},markers:[{id:"return",kind:"dungeonReturn",x:1,y:1},{id:"down",kind:"stairs",x:2,y:2}]}; old.terrain.fill("dungeon.floor"); delete old.collision; const migrated=normalizeMap(old); expect(migrated.version).toBe(6); expect(migrated.enemyRoster).toEqual([]); expect(migrated.markers.find((marker)=>marker.id==="return")).toMatchObject({kind:"stairsUp",visual:{assetId:"dungeon.stairs-up",frame:0}}); expect(migrated.markers.find((marker)=>marker.id==="down")).toMatchObject({kind:"stairsDown",visual:{assetId:"dungeon.stairs-down",frame:0}}); expect(migrated.layers.ground[0]).toEqual({assetId:"dungeon.floor",frame:0}); });
});
